// Autogenerated Arkos AKY player for MSX-GL library 
// On 10/01/2022 et 18:11:52, 57    
#include "aky_player.h" 
void AKY_Dummy()         
{                         
__asm                     
PLY_AKY_START:
__endasm;
}

// Initialize a music
void AKY_Init(const void* data, u16 sng)
{
__asm
	ld a, e ; convert C parameter
PLY_AKY_INIT:
PLY_AKY_USEHOOKS:
	inc hl
PLY_AKY_OFFSET1B:
	ld a, (hl)
PLY_AKY_RRB_SOUNDCHANNELBIT:
	inc hl
PLY_AKY_RRB_NOISECHANNELBIT = .+2
    ld de, #0x4
PLY_AKY_INIT_SKIPHEADERLOOP:
	add hl, de
    sub #0x3
    jr z, PLY_AKY_INIT_SKIPHEADEREND
    jr nc, PLY_AKY_INIT_SKIPHEADERLOOP
PLY_AKY_INIT_SKIPHEADEREND:
	ld (PLY_AKY_PATTERNFRAMECOUNTER_OVER+1), hl
    ld a, #0xb7
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE), a
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE), a
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE), a
    ld hl, #0x1
    ld (PLY_AKY_PATTERNFRAMECOUNTER+1), hl
    ret 
__endasm;
}

// Play a music frame
void AKY_Decode()
{
__asm
PLY_AKY_PLAY:
	ld (PLY_AKY_PSGREGISTER13_END+1), sp
PLY_AKY_PATTERNFRAMECOUNTER:
	ld hl, #0x1
    dec hl
    ld a, l
    or h
    jr z, PLY_AKY_PATTERNFRAMECOUNTER_OVER
    ld (PLY_AKY_PATTERNFRAMECOUNTER+1), hl
    jr PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK
PLY_AKY_PATTERNFRAMECOUNTER_OVER:
PLY_AKY_PTLINKER:
	ld sp, #0x0
    pop hl
PLY_AKY_OPCODE_SCF:
	ld a, l
    or h
    jr nz, PLY_AKY_LINKERNOTENDSONG
    pop hl
    ld sp, hl
    pop hl
PLY_AKY_LINKERNOTENDSONG:
	ld (PLY_AKY_PATTERNFRAMECOUNTER+1), hl
    pop hl
    ld (PLY_AKY_CHANNEL1_PTTRACK+1), hl
    pop hl
    ld (PLY_AKY_CHANNEL2_PTTRACK+1), hl
    pop hl
    ld (PLY_AKY_CHANNEL3_PTTRACK+1), hl
    ld (PLY_AKY_PATTERNFRAMECOUNTER_OVER+1), sp
    ld a, #0x1
    ld (PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK+1), a
    ld (PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK+1), a
    jr PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_OVER
PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK:
	ld a, #0x1
    dec a
    jr nz, PLY_AKY_CHANNEL1_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a, #0xb7
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE), a
PLY_AKY_CHANNEL1_PTTRACK:
	ld sp, #0x0
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL1_PTTRACK+1), sp
    ld (PLY_AKY_CHANNEL1_PTREGISTERBLOCK+1), hl
PLY_AKY_CHANNEL1_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK+1), a
PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK:
	ld a, #0x1
    dec a
    jr nz, PLY_AKY_CHANNEL2_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a, #0xb7
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE), a
PLY_AKY_CHANNEL2_PTTRACK:
	ld sp, #0x0
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL2_PTTRACK+1), sp
    ld (PLY_AKY_CHANNEL2_PTREGISTERBLOCK+1), hl
PLY_AKY_CHANNEL2_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK+1), a
PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK:
	ld a, #0x1
    dec a
    jr nz, PLY_AKY_CHANNEL3_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a, #0xb7
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE), a
PLY_AKY_CHANNEL3_PTTRACK:
	ld sp, #0x0
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL3_PTTRACK+1), sp
    ld (PLY_AKY_CHANNEL3_PTREGISTERBLOCK+1), hl
PLY_AKY_CHANNEL3_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK+1), a
    ld hl, #0x8
    ld de, #0xf4f6
    ld bc, #0xf690
    ld a, #0xc0
    out (c), a
    ex af, af'
PLY_AKY_OPCODE_OR_A:
	exx
    ld bc, #0xe0ff
    ld sp, #PLY_AKY_RETTABLE_READREGISTERBLOCK
PLY_AKY_CHANNEL1_PTREGISTERBLOCK:
	ld hl, #0x0
PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE:
	or a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL1_REGISTERBLOCK_RETURN:
	ld a, #0x37
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE), a
    ld (PLY_AKY_CHANNEL1_PTREGISTERBLOCK+1), hl
    srl b
PLY_AKY_CHANNEL2_PTREGISTERBLOCK:
	ld hl, #0x0
PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE:
	or a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL2_REGISTERBLOCK_RETURN:
	ld a, #0x37
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE), a
    ld (PLY_AKY_CHANNEL2_PTREGISTERBLOCK+1), hl
    rr b
PLY_AKY_CHANNEL3_PTREGISTERBLOCK:
	ld hl, #0x0
PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE:
	or a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL3_REGISTERBLOCK_RETURN:
	ld a, #0x37
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE), a
    ld (PLY_AKY_CHANNEL3_PTREGISTERBLOCK+1), hl
    ld a, b
    exx
    inc h
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    dec h
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld hl, #PLY_AKY_PSGREGISTER6
    dec b
    outi
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    ld a, #0xb
    ld b, d
    out (c), a
    ld b, e
    .db 0xed
    .db 0x71
    dec b
    outi
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc a
    ld b, d
    out (c), a
    ld b, e
    .db 0xed
    .db 0x71
    dec b
    outi
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
PLY_AKY_PSGREGISTER13_CODE:
	ld a, (hl)
PLY_AKY_PSGREGISTER13_RETRIG:
	cp #0xff
    jr z, PLY_AKY_PSGREGISTER13_END
    ld (PLY_AKY_PSGREGISTER13_RETRIG+1), a
    ld b, d
    ld l, #0xd
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
PLY_AKY_PSGREGISTER13_END:
PLY_AKY_EXIT:
	ld sp, #0x0
    ret 
PLY_AKY_READREGISTERBLOCK:
	ld a, (hl)
    inc hl
    jp c, PLY_AKY_RRB_NONINITIALSTATE
    rra 
    jr c, PLY_AKY_RRB_IS_SOFTWAREONLYORSOFTWAREANDHARDWARE
    rra 
    jr c, PLY_AKY_RRB_IS_HARDWAREONLY
PLY_AKY_RRB_IS_NOSOFTWARENOHARDWARE:
	rra 
    jr nc, PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_READVOLUME
    ld de, #PLY_AKY_PSGREGISTER6
    ldi
    res 5, b
PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_READVOLUME:
	exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    inc h
    inc h
    exx
    set 2, b
    ret 
PLY_AKY_RRB_IS_HARDWAREONLY:
	rra 
    jr nc, PLY_AKY_RRB_IS_HO_NORETRIG
    set 7, a
    ld (PLY_AKY_PSGREGISTER13_RETRIG+1), a
PLY_AKY_RRB_IS_HO_NORETRIG:
	rra 
    jr nc, PLY_AKY_RRB_IS_HO_NONOISE
    ld de, #PLY_AKY_PSGREGISTER6
    ldi
    res 5, b
PLY_AKY_RRB_IS_HO_NONOISE:
	and #0xf
    ld (PLY_AKY_PSGREGISTER13), a
    ld de, #PLY_AKY_PSGREGISTER11
    ldi
    ldi
    set 2, b
    exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), c
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    inc h
    inc h
    exx
    ret 
PLY_AKY_RRB_IS_SOFTWAREONLYORSOFTWAREANDHARDWARE:
	rra 
    jr c, PLY_AKY_RRB_IS_SOFTWAREANDHARDWARE
    rra 
    jr nc, PLY_AKY_RRB_IS_SOFTWAREONLY_NONOISE
    ld de, #PLY_AKY_PSGREGISTER6
    ldi
    res 5, b
PLY_AKY_RRB_IS_SOFTWAREONLY_NONOISE:
	exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    exx
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc h
    exx
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc h
    exx
    ret 
PLY_AKY_RRB_IS_SOFTWAREANDHARDWARE:
	rra 
    jr nc, PLY_AKY_RRB_IS_SAH_NORETRIG
    set 7, a
    ld (PLY_AKY_PSGREGISTER13_RETRIG+1), a
PLY_AKY_RRB_IS_SAH_NORETRIG:
	rra 
    jr nc, PLY_AKY_RRB_IS_SAH_NONOISE
    ld de, #PLY_AKY_PSGREGISTER6
    ldi
    res 5, b
PLY_AKY_RRB_IS_SAH_NONOISE:
	and #0xf
    ld (PLY_AKY_PSGREGISTER13), a
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc h
    exx
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc h
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), c
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    exx
    ld de, #PLY_AKY_PSGREGISTER11
    ldi
    ldi
    ret 
PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_LOOP:
	ld a, (hl)
    inc hl
    ld h, (hl)
    ld l, a
    ld a, (hl)
    inc hl
PLY_AKY_RRB_NONINITIALSTATE:
	rra 
    jr c, PLY_AKY_RRB_NIS_SOFTWAREONLYORSOFTWAREANDHARDWARE
    rra 
    jp c, PLY_AKY_RRB_NIS_HARDWAREONLY
    ld e, a
    and #0x3
    cp #0x2
    jr z, PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_LOOP
    set 2, b
    ld a, e
    rra 
    jr nc, PLY_AKY_RRB_NIS_NOVOLUME
    and #0xf
    exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    exx
PLY_AKY_RRB_NIS_NOVOLUME:
	exx
    inc l
    inc h
    inc h
    exx
    bit 5, e
    ret z
    ld a, (hl)
    ld (PLY_AKY_PSGREGISTER6), a
    inc hl
    res 5, b
    ret 
PLY_AKY_RRB_NIS_SOFTWAREONLYORSOFTWAREANDHARDWARE:
	rra 
    jp c, PLY_AKY_RRB_NIS_SOFTWAREANDHARDWARE
    ld e, a
    and #0xf
    exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    exx
    bit 4, e
    jr z, PLY_AKY_RRB_NIS_SOFTWAREONLY_NOLSP
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    exx
PLY_AKY_RRB_NIS_SOFTWAREONLY_NOLSP:
	bit 5, e
    jr nz, PLY_AKY_RRB_NIS_SOFTWAREONLY_MSPANDMAYBENOISE
    exx
    inc h
    inc h
    exx
    ret 
PLY_AKY_RRB_NIS_SOFTWAREONLY_MSPANDMAYBENOISE:
	ld a, (hl)
    inc hl
    exx
    inc h
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc h
    exx
    rla 
    ret nc
    res 5, b
    rla 
    ret nc
    ld de, #PLY_AKY_PSGREGISTER6
    ldi
    ret 
PLY_AKY_RRB_NIS_HARDWAREONLY:
	rla 
    ld e, a
    and #0xe
    ld (PLY_AKY_PSGREGISTER13), a
    set 2, b
    exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), c
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    inc h
    inc h
    exx
    ld a, e
    rla 
    rla 
    jr nc, PLY_AKY_RRB_NIS_HARDWAREONLY_NOLSB
    ld de, #PLY_AKY_PSGREGISTER11
    ldi
PLY_AKY_RRB_NIS_HARDWAREONLY_NOLSB:
	rla 
    jr nc, PLY_AKY_RRB_NIS_HARDWAREONLY_NOMSB
    ld de, #PLY_AKY_PSGREGISTER12
    ldi
PLY_AKY_RRB_NIS_HARDWAREONLY_NOMSB:
	rla 
    jr c, PLY_AKY_RRB_NIS_HARDWARE_SHARED_NOISEORRETRIG_ANDSTOP
    ret 
PLY_AKY_RRB_NIS_SOFTWAREANDHARDWARE:
	exx
    ld b, d
    out (c), l
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), c
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    inc l
    exx
    rra 
    jr nc, PLY_AKY_RRB_NIS_SAHH_AFTERLSBH
    ld de, #PLY_AKY_PSGREGISTER11
    ldi
PLY_AKY_RRB_NIS_SAHH_AFTERLSBH:
	rra 
    jr nc, PLY_AKY_RRB_NIS_SAHH_AFTERMSBH
    ld de, #PLY_AKY_PSGREGISTER12
    ldi
PLY_AKY_RRB_NIS_SAHH_AFTERMSBH:
	rra 
    jr nc, PLY_AKY_RRB_NIS_SAHH_AFTERLSBS
    ld e, a
    ld a, (hl)
    inc hl
    exx
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    exx
    ld a, e
PLY_AKY_RRB_NIS_SAHH_AFTERLSBS:
	rra 
    jr nc, PLY_AKY_RRB_NIS_SAHH_AFTERMSBS
    ld e, a
    ld a, (hl)
    inc hl
    exx
    inc h
    ld b, d
    out (c), h
    ld b, e
    .db 0xed
    .db 0x71
    ld b, d
    out (c), a
    ld b, e
    out (c), c
    ex af, af'
    out (c), a
    ex af, af'
    dec h
    exx
    ld a, e
PLY_AKY_RRB_NIS_SAHH_AFTERMSBS:
	exx
    inc h
    inc h
    exx
    rra 
    jr nc, PLY_AKY_RRB_NIS_SAHH_AFTERENVELOPE
    ld de, #PLY_AKY_PSGREGISTER13
    ldi
PLY_AKY_RRB_NIS_SAHH_AFTERENVELOPE:
	rra 
    ret nc
PLY_AKY_RRB_NIS_HARDWARE_SHARED_NOISEORRETRIG_ANDSTOP:
	ld a, (hl)
    inc hl
    rra 
    jr nc, PLY_AKY_RRB_NIS_S_NOR_NORETRIG
    set 7, a
    ld (PLY_AKY_PSGREGISTER13_RETRIG+1), a
PLY_AKY_RRB_NIS_S_NOR_NORETRIG:
	rra 
    ret nc
    res 5, b
    rra 
    ret nc
    ld (PLY_AKY_PSGREGISTER6), a
    ret 
PLY_AKY_PSGREGISTER6:
	.db 0x0
PLY_AKY_PSGREGISTER11:
	.db 0x0
PLY_AKY_PSGREGISTER12:
	.db 0x0
PLY_AKY_PSGREGISTER13:
	.db 0x0
PLY_AKY_RETTABLE_READREGISTERBLOCK:
	.dw PLY_AKY_CHANNEL1_REGISTERBLOCK_RETURN
    .dw PLY_AKY_CHANNEL2_REGISTERBLOCK_RETURN
    .dw PLY_AKY_CHANNEL3_REGISTERBLOCK_RETURN
__endasm;                 
}                         
