; ____________________________                                                 
; ██▀▀█▀▀██▀▀▀▀▀▀▀█▀▀█        │   ▄▄       ▄▄                                  
; ██  ▀  █▄  ▀██▄ ▀ ▄█ ▄▀▀ █  │  ██▄█ ██▄▀ ██▄▀ ▄█▀▄  ██▀                      
; █  █ █  ▀▀  ▄█  █  █ ▀▄█ █▄ │  ██ █ ██   ██ █ ▀█▄▀ ▄██                       
; ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀────────┘                                                
;  by Guillaume 'Aoineko' Blanchard under CC BY-SA license                     
;==============================================================================
; Autogenerated Arkos AKY player for MSX-GL library                           
;  on 04/12/2025 at  1:03:36,52                                                         
;                                                                              
; Arkos Tracker and the Z80 players are coded and designed                     
;  by Julien Névo (aka Targhan/Arkos) under MIT License.                       
;==============================================================================
PLY_AKY_PSGREGISTER_OFFSETREGISTERSOFTWAREPERIODMSB = .+1
PLY_AKY_PSGREGISTER_OFFSETREGISTERHARDWAREPERIODMSB = .+1
PLY_AKY_PSGREGISTER_OFFSETREGISTERHARDWAREENVELOPE = .+2
PLY_AKY_RRB_SOUNDCHANNELBIT = .+2
PLY_AKY_SOUNDEFFECTDATA_OFFSETINVERTEDVOLUME = .+2
PLY_AKY_START:
PLY_AKY_PSGREGISTER_OFFSETREGISTERSOFTWAREPERIODLSB:
PLY_AKY_OPCODE_OR_A:
PLY_AKY_OFFSET1B:
PLY_AKY_PSGREGISTER_OFFSETREGISTERHARDWAREPERIODLSB:
	jp PLY_AKY_INIT
PLY_AKY_SOUNDEFFECTDATA_OFFSETSPEED = .+1
PLY_AKY_PSGREGISTER_OFFSETREGISTERNOISE = .+1
PLY_AKY_PSG1HARDWAREREGISTERARRAY_SIZE = .+2
PLY_AKY_RRB_NOISECHANNELBIT = .+2
PLY_AKY_PSGREGISTER_OFFSETRETRIG:
PLY_AKY_SOUNDEFFECTDATA_OFFSETCURRENTSTEP:
	jp PLY_AKY_PLAY
_PLY_AKY_INITSOUNDEFFECTS::
PLY_AKY_INITSOUNDEFFECTS:
PLY_AKY_PSGREGISTER_OFFSETREGISTERVOLUME:
	ld (PLY_AKY_PTSOUNDEFFECTTABLE),hl
    ret 
_PLY_AKY_PLAYSOUNDEFFECT::
PLY_AKY_PLAYSOUNDEFFECT:
	dec a
PLY_AKY_PSG1SOFTWAREREGISTERARRAY_SIZE:
	ld hl,(PLY_AKY_PTSOUNDEFFECTTABLE)
    ld e,a
    ld d,#0x0
    add hl,de
    add hl,de
    ld e,(hl)
    inc hl
    ld d,(hl)
    ld a,(de)
    inc de
    ex af,af' ;'
    ld a,b
    ld hl,#PLY_AKY_CHANNEL1_SOUNDEFFECTDATA
    ld b,#0x0
    sla c
    sla c
    sla c
    add hl,bc
    ld (hl),e
    inc hl
    ld (hl),d
    inc hl
    ld (hl),a
    inc hl
    ld (hl),#0x0
    inc hl
    ex af,af' ;'
    ld (hl),a
    ret 
_PLY_AKY_STOPSOUNDEFFECTFROMCHANNEL::
PLY_AKY_STOPSOUNDEFFECTFROMCHANNEL:
	add a,a
    add a,a
    add a,a
    ld e,a
    ld d,#0x0
    ld hl,#PLY_AKY_CHANNEL1_SOUNDEFFECTDATA
    add hl,de
    ld (hl),d
    inc hl
    ld (hl),d
    ret 
PLY_AKY_PLAYSOUNDEFFECTSSTREAM:
	rla 
    rla 
    ld ix,#PLY_AKY_CHANNEL1_SOUNDEFFECTDATA
    ld iy,#PLY_AKY_SFXREG8
    ld hl,#PLY_AKY_SFXPSGREGISTERARRAY
    exx
    ld c,a
    call PLY_AKY_PSES_PLAY
    ld ix,#PLY_AKY_CHANNEL2_SOUNDEFFECTDATA
    ld iy,#PLY_AKY_SFXREG9
    exx
    ld hl,#PLY_AKY_SFXREG23
    exx
    srl c
    call PLY_AKY_PSES_PLAY
    ld ix,#PLY_AKY_CHANNEL3_SOUNDEFFECTDATA
    ld iy,#PLY_AKY_SFXREG10
    exx
    ld hl,#PLY_AKY_SFXREG45
    exx
    scf
    rr c
    call PLY_AKY_PSES_PLAY
    ld a,c
    ret 
PLY_AKY_PSES_PLAY:
	ld l,+0(ix)
    ld h,+1(ix)
    ld a,l
    or h
    ret z
PLY_AKY_PSES_READFIRSTBYTE:
	ld a,(hl)
    inc hl
PLY_AKY_PLAYCITY_SELECTWRITE_PORT_LSB_RIGHT:
	ld b,a
    rra 
    jr c,PLY_AKY_PSES_SOFTWAREORSOFTWAREANDHARDWARE
PLY_AKY_PLAYCITY_SELECTWRITE_PORT_LSB_LEFT:
	rra 
    jr c,PLY_AKY_PSES_HARDWAREONLY
    rra 
    jr c,PLY_AKY_PSES_S_ENDORLOOP
    call PLY_AKY_PSES_MANAGEVOLUMEFROMA_FILTER4BITS
    rl b
    call PLY_AKY_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
    set 2,c
    jr PLY_AKY_PSES_SAVEPOINTERANDEXIT
PLY_AKY_PSES_S_ENDORLOOP:
	rra 
    jr c,PLY_AKY_PSES_S_LOOP
    xor a
    ld +0(ix),a
    ld +1(ix),a
    ret 
PLY_AKY_PSES_S_LOOP:
	ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    jr PLY_AKY_PSES_READFIRSTBYTE
PLY_AKY_PSES_SAVEPOINTERANDEXIT:
	ld a,+3(ix)
    cp +4(ix)
    jr c,PLY_AKY_PSES_NOTREACHED
    ld +3(ix),#0x0
    .db 0xdd
    .db 0x75
    .db 0x0
    .db 0xdd
    .db 0x74
    .db 0x1
    ret 
PLY_AKY_PSES_NOTREACHED:
	inc +3(ix)
    ret 
PLY_AKY_PSES_HARDWAREONLY:
	call PLY_AKY_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE
    set 2,c
    jr PLY_AKY_PSES_SAVEPOINTERANDEXIT
PLY_AKY_PSES_SOFTWAREORSOFTWAREANDHARDWARE:
	rra 
    jr c,PLY_AKY_PSES_SOFTWAREANDHARDWARE
    call PLY_AKY_PSES_MANAGEVOLUMEFROMA_FILTER4BITS
    rl b
    call PLY_AKY_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
    res 2,c
    call PLY_AKY_PSES_READSOFTWAREPERIOD
    jr PLY_AKY_PSES_SAVEPOINTERANDEXIT
PLY_AKY_PSES_SOFTWAREANDHARDWARE:
	call PLY_AKY_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE
    call PLY_AKY_PSES_READSOFTWAREPERIOD
    res 2,c
    jr PLY_AKY_PSES_SAVEPOINTERANDEXIT
PLY_AKY_PSES_SHARED_READRETRIGHARDWAREENVPERIODNOISE:
	rra 
    jr nc,PLY_AKY_PSES_H_AFTERRETRIG
    ld d,a
    ld a,#0xff
    ld (PLY_AKY_SFXRETRIG),a
    ld a,d
PLY_AKY_PSES_H_AFTERRETRIG:
	and #0x7
    add a,#0x8
    ld (PLY_AKY_SFXREG13),a
    rl b
PLY_AKY_PLAYCITY_SELECT_PORT_MSB = .+1
PLY_AKY_PLAYCITY_WRITE_PORT_MSB:
	call PLY_AKY_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL
PLY_AKY_SPECNEXT_PSG3_REGISTER = .+2
    call PLY_AKY_PSES_READHARDWAREPERIOD
PLY_AKY_OPCODE_SCF = .+1
PLY_AKY_TURBOSOUND_PSG1_REGISTER = .+1
PLY_AKY_SPECNEXT_PSG1_REGISTER = .+1
PLY_AKY_PCW_TURBOSOUND_PSGNUMBER1_SELECTION_VALUE = .+1
PLY_AKY_TURBOSOUND_PSG2_REGISTER:
PLY_AKY_PCW_TURBOSOUND_PSGNUMBER2_SELECTION_VALUE:
PLY_AKY_SPECNEXT_PSG2_REGISTER:
	ld a,#0x10
    jp PLY_AKY_PSES_MANAGEVOLUMEFROMA_HARD
PLY_AKY_PSES_READNOISEIFNEEDEDANDOPENORCLOSENOISECHANNEL:
	jr c,PLY_AKY_PSES_READNOISEANDOPENNOISECHANNEL_OPENNOISE
    set 5,c
    ret 
PLY_AKY_PSES_READNOISEANDOPENNOISECHANNEL_OPENNOISE:
	ld a,(hl)
    ld (PLY_AKY_SFXREG6),a
    inc hl
    res 5,c
    ret 
PLY_AKY_PSES_READHARDWAREPERIOD:
	ld a,(hl)
    ld (PLY_AKY_SFXHARDWAREPERIOD),a
    inc hl
    ld a,(hl)
    ld (PLY_AKY_SFXHARDWAREPERIOD+1),a
    inc hl
    ret 
PLY_AKY_PSES_READSOFTWAREPERIOD:
	ld a,(hl)
    inc hl
    exx
    ld (hl),a
    inc hl
    exx
    ld a,(hl)
    inc hl
    exx
    ld (hl),a
    exx
    ret 
PLY_AKY_PSES_MANAGEVOLUMEFROMA_FILTER4BITS:
	and #0xf
PLY_AKY_PSES_MANAGEVOLUMEFROMA_HARD:
	sub +2(ix)
    jr nc,PLY_AKY_PSES_MVFA_NOOVERFLOW
    xor a
PLY_AKY_PSES_MVFA_NOOVERFLOW:
	ld +0(iy),a
    ret 
_PLY_AKY_INIT::
PLY_AKY_INIT:
	inc hl
    ld a,(hl)
    inc hl
    ld de,#0x4
    add hl,de
    ld (PLY_AKY_PSG1HARDWAREREGISTERARRAY_END),hl
    ld a,#0x0
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE),a
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE),a
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE),a
    ld hl,#0x1
    ld (PLY_AKY_PATTERNFRAMECOUNTER),hl
    ld hl,#0x0
    ld (PLY_AKY_CHANNEL1_SOUNDEFFECTDATA),hl
    ld (PLY_AKY_CHANNEL2_SOUNDEFFECTDATA),hl
    ld (PLY_AKY_CHANNEL3_SOUNDEFFECTDATA),hl
    ret 
_PLY_AKY_PLAY::
PLY_AKY_PLAY:
	ld (PLY_AKY_SAVESP),sp
    ld hl,(PLY_AKY_PATTERNFRAMECOUNTER)
    dec hl
    ld a,l
    or h
    jr z,PLY_AKY_PATTERNFRAMECOUNTER_OVER
    ld (PLY_AKY_PATTERNFRAMECOUNTER),hl
    jr PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_START
PLY_AKY_PATTERNFRAMECOUNTER_OVER:
	ld sp,(PLY_AKY_PSG1HARDWAREREGISTERARRAY_END)
    pop hl
    ld a,l
    or h
    jr nz,PLY_AKY_LINKERNOTENDSONG
    pop hl
    ld sp,hl
    pop hl
PLY_AKY_LINKERNOTENDSONG:
	ld (PLY_AKY_PATTERNFRAMECOUNTER),hl
    pop hl
    ld (PLY_AKY_CHANNEL1_PTTRACK),hl
    pop hl
    ld (PLY_AKY_CHANNEL2_PTTRACK),hl
    pop hl
    ld (PLY_AKY_CHANNEL3_PTTRACK),hl
    ld (PLY_AKY_PSG1HARDWAREREGISTERARRAY_END),sp
    ld a,#0x1
    ld (PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK),a
    ld (PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK),a
    jr PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_OVER
PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_START:
	ld a,(PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK)
    dec a
    jr nz,PLY_AKY_CHANNEL1_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a,#0x0
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE),a
    ld sp,(PLY_AKY_CHANNEL1_PTTRACK)
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL1_PTTRACK),sp
    ld (PLY_AKY_CHANNEL1_PTREGISTERBLOCK),hl
PLY_AKY_CHANNEL1_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK),a
PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK_START:
	ld a,(PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK)
    dec a
    jr nz,PLY_AKY_CHANNEL2_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a,#0x0
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE),a
    ld sp,(PLY_AKY_CHANNEL2_PTTRACK)
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL2_PTTRACK),sp
    ld (PLY_AKY_CHANNEL2_PTREGISTERBLOCK),hl
PLY_AKY_CHANNEL2_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK),a
PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK_START:
	ld a,(PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK)
    dec a
    jr nz,PLY_AKY_CHANNEL3_REGISTERBLOCK_PROCESS
PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK_OVER:
	ld a,#0x0
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE),a
    ld sp,(PLY_AKY_CHANNEL3_PTTRACK)
    dec sp
    pop af
    pop hl
    ld (PLY_AKY_CHANNEL3_PTTRACK),sp
    ld (PLY_AKY_CHANNEL3_PTREGISTERBLOCK),hl
PLY_AKY_CHANNEL3_REGISTERBLOCK_PROCESS:
	ld (PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK),a
    ld sp,#PLY_AKY_RETTABLE_READREGISTERBLOCK
    ld iy,#PLY_AKY_PSG1HARDWAREREGISTERARRAY
    ld b,#0xe0
    ld ix,#PLY_AKY_PSG1REGISTER0
    ld hl,(PLY_AKY_CHANNEL1_PTREGISTERBLOCK)
    ld a,(PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE)
    add a,a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL1_REGISTERBLOCK_RETURN:
	ld a,#0xff
    ld (PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE),a
    ld (PLY_AKY_CHANNEL1_PTREGISTERBLOCK),hl
    srl b
    ld ix,#PLY_AKY_PSG1REGISTER2
    ld hl,(PLY_AKY_CHANNEL2_PTREGISTERBLOCK)
    ld a,(PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE)
    add a,a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL2_REGISTERBLOCK_RETURN:
	ld a,#0xff
    ld (PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE),a
    ld (PLY_AKY_CHANNEL2_PTREGISTERBLOCK),hl
    scf
    rr b
    ld ix,#PLY_AKY_PSG1REGISTER4
    ld hl,(PLY_AKY_CHANNEL3_PTREGISTERBLOCK)
    ld a,(PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE)
    add a,a
    jp PLY_AKY_READREGISTERBLOCK
PLY_AKY_CHANNEL3_REGISTERBLOCK_RETURN:
	ld a,#0xff
    ld (PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE),a
    ld (PLY_AKY_CHANNEL3_PTREGISTERBLOCK),hl
    ld a,b
    ld hl,#PLY_AKY_PSG1REGISTER0
    ld de,#PLY_AKY_SFXPSGREGISTERARRAY
    ld bc,#PLY_AKY_PSG1SOFTWAREREGISTERARRAY_SIZE+5
    ldir
    ld (PLY_AKY_SAVESPTEMP),sp
    ld sp,(PLY_AKY_SAVESP)
    call PLY_AKY_PLAYSOUNDEFFECTSSTREAM
    ld b,a
    ld sp,(PLY_AKY_SAVESPTEMP)
    ld hl,#PLY_AKY_SFXPSGREGISTERARRAY
    ret 
PLY_AKY_PSG1AFTERSENDINGPSGREGISTERS:
	ld a,(PLY_AKY_SFXRETRIG)
    ld (PLY_AKY_PSG1RETRIG),a
    ld sp,(PLY_AKY_SAVESP)
    ret 
PLY_AKY_READREGISTERBLOCK:
	ld a,(hl)
    inc hl
    jp c,PLY_AKY_RRB_NONINITIALSTATE
    rra 
    jr c,PLY_AKY_RRB_IS_SOFTWAREONLYORSOFTWAREANDHARDWARE
    rra 
    jr c,PLY_AKY_RRB_IS_HARDWAREONLY
PLY_AKY_RRB_IS_NOSOFTWARENOHARDWARE:
	rra 
    jr nc,PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_READVOLUME
    ld c,(hl)
    inc hl
    ld +4(iy),c
    res 5,b
PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_READVOLUME:
	ld +6(ix),a
    set 2,b
    ret 
PLY_AKY_RRB_IS_HARDWAREONLY:
	rra 
    jr nc,PLY_AKY_RRB_IS_HO_NORETRIG
    ld +3(iy),#0xff
PLY_AKY_RRB_IS_HO_NORETRIG:
	rra 
    jr nc,PLY_AKY_RRB_IS_HO_NONOISE
    ld c,(hl)
    inc hl
    ld +4(iy),c
    res 5,b
PLY_AKY_RRB_IS_HO_NONOISE:
	and #0xf
    ld +2(iy),a
    ld a,(hl)
    inc hl
    ld +0(iy),a
    ld a,(hl)
    inc hl
    ld +1(iy),a
    set 2,b
    ld +6(ix),#0x10
    ret 
PLY_AKY_RRB_IS_SOFTWAREONLYORSOFTWAREANDHARDWARE:
	rra 
    jr c,PLY_AKY_RRB_IS_SOFTWAREANDHARDWARE
    rra 
    jr nc,PLY_AKY_RRB_IS_SOFTWAREONLY_NONOISE
    ld c,(hl)
    inc hl
    ld +4(iy),c
    res 5,b
PLY_AKY_RRB_IS_SOFTWAREONLY_NONOISE:
	ld +6(ix),a
    ld a,(hl)
    inc hl
    ld +0(ix),a
    ld a,(hl)
    inc hl
    ld +1(ix),a
    ret 
PLY_AKY_RRB_IS_SOFTWAREANDHARDWARE:
	rra 
    jr nc,PLY_AKY_RRB_IS_SAH_NORETRIG
    ld +3(iy),#0xff
PLY_AKY_RRB_IS_SAH_NORETRIG:
	rra 
    jr nc,PLY_AKY_RRB_IS_SAH_NONOISE
    ld c,(hl)
    inc hl
    ld +4(iy),c
    res 5,b
PLY_AKY_RRB_IS_SAH_NONOISE:
	and #0xf
    ld +2(iy),a
    ld a,(hl)
    inc hl
    ld +0(ix),a
    ld a,(hl)
    inc hl
    ld +1(ix),a
    ld +6(ix),#0x10
    ld a,(hl)
    inc hl
    ld +0(iy),a
    ld a,(hl)
    inc hl
    ld +1(iy),a
    ret 
PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_LOOP:
	ld a,(hl)
    inc hl
    ld h,(hl)
    ld l,a
    ld a,(hl)
    inc hl
PLY_AKY_RRB_NONINITIALSTATE:
	rra 
    jr c,PLY_AKY_RRB_NIS_SOFTWAREONLYORSOFTWAREANDHARDWARE
    rra 
    jp c,PLY_AKY_RRB_NIS_HARDWAREONLY
    ld e,a
    and #0x3
    cp #0x2
    jr z,PLY_AKY_RRB_NIS_NOSOFTWARENOHARDWARE_LOOP
    set 2,b
    ld a,e
    rra 
    jr nc,PLY_AKY_RRB_NIS_NOVOLUME
    and #0xf
    ld +6(ix),a
PLY_AKY_RRB_NIS_NOVOLUME:
	bit 5,e
    ret z
    ld c,(hl)
    inc hl
    ld +4(iy),c
    res 5,b
    ret 
PLY_AKY_RRB_NIS_SOFTWAREONLYORSOFTWAREANDHARDWARE:
	rra 
    jp c,PLY_AKY_RRB_NIS_SOFTWAREANDHARDWARE
    ld e,a
    and #0xf
    ld +6(ix),a
    bit 4,e
    jr z,PLY_AKY_RRB_NIS_SOFTWAREONLY_NOLSP
    ld a,(hl)
    inc hl
    ld +0(ix),a
PLY_AKY_RRB_NIS_SOFTWAREONLY_NOLSP:
	bit 5,e
    ret z
    ld a,(hl)
    inc hl
    ld +1(ix),a
    rla 
    ret nc
    res 5,b
    rla 
    ret nc
    ld c,(hl)
    inc hl
    ld +4(iy),c
    ret 
PLY_AKY_RRB_NIS_HARDWAREONLY:
	ld e,a
    and #0x7
    or #0x8
    ld +2(iy),a
    set 2,b
    ld +6(ix),#0x10
    ld a,e
    rla 
    rla 
    rla 
    jr nc,PLY_AKY_RRB_NIS_HARDWAREONLY_NOLSB
    ld c,(hl)
    inc hl
    ld +0(iy),c
PLY_AKY_RRB_NIS_HARDWAREONLY_NOLSB:
	rla 
    jr nc,PLY_AKY_RRB_NIS_HARDWAREONLY_NOMSB
    ld c,(hl)
    inc hl
    ld +1(iy),c
PLY_AKY_RRB_NIS_HARDWAREONLY_NOMSB:
	rla 
    jr c,PLY_AKY_RRB_NIS_HARDWARE_SHARED_NOISEORRETRIG_ANDSTOP
    ret 
PLY_AKY_RRB_NIS_SOFTWAREANDHARDWARE:
	ld +6(ix),#0x10
    rra 
    jr nc,PLY_AKY_RRB_NIS_SAHH_AFTERLSBH
    ld c,(hl)
    inc hl
    ld +0(iy),c
PLY_AKY_RRB_NIS_SAHH_AFTERLSBH:
	rra 
    jr nc,PLY_AKY_RRB_NIS_SAHH_AFTERMSBH
    ld c,(hl)
    inc hl
    ld +1(iy),c
PLY_AKY_RRB_NIS_SAHH_AFTERMSBH:
	rra 
    jr nc,PLY_AKY_RRB_NIS_SAHH_AFTERLSBS
    ld c,(hl)
    inc hl
    .db 0xdd
    .db 0x71
    .db 0x0
PLY_AKY_RRB_NIS_SAHH_AFTERLSBS:
	rra 
    jr nc,PLY_AKY_RRB_NIS_SAHH_AFTERMSBS
    ld c,(hl)
    inc hl
    .db 0xdd
    .db 0x71
    .db 0x1
PLY_AKY_RRB_NIS_SAHH_AFTERMSBS:
	rra 
    jr nc,PLY_AKY_RRB_NIS_SAHH_AFTERENVELOPE
    ld c,(hl)
    inc hl
    ld +2(iy),c
PLY_AKY_RRB_NIS_SAHH_AFTERENVELOPE:
	rra 
    ret nc
PLY_AKY_RRB_NIS_HARDWARE_SHARED_NOISEORRETRIG_ANDSTOP:
	ld a,(hl)
    inc hl
    rra 
    jr nc,PLY_AKY_RRB_NIS_S_NOR_NORETRIG
    ld +3(iy),#0xff
PLY_AKY_RRB_NIS_S_NOR_NORETRIG:
	rra 
    ret nc
    res 5,b
    rra 
    ret nc
    ld +4(iy),a
    ret 
PLY_AKY_SENDPSGREGISTERS_FASTPSGACCESS_A0_A1:
	ld a,#0x7
    out (0xa0),a
    ld a,b
    out (0xa1),a
    xor a
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x1
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x2
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x3
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x4
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x5
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0x8
    out (0xa0),a
    ld a,(hl)
    out (0xa1),a
    inc hl
    inc hl
    ld a,#0x9
    out (0xa0),a
    ld a,(hl)
    out (0xa1),a
PLY_AKY_REGISTER9END:
	inc hl
    inc hl
    ld a,#0xa
    out (0xa0),a
    ld a,(hl)
    out (0xa1),a
PLY_AKY_REGISTER10END:
	inc hl
    ld a,#0xb
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0xc
    out (0xa0),a
    ld a,(hl)
    inc hl
    out (0xa1),a
    ld a,#0xd
    out (0xa0),a
    ld a,(hl)
    inc hl
    cp (hl)
    jr z,PLY_AKY_SENDPSGREGISTERS_FASTPSGACCESS_A0_A1_REGISTER13_END
    ld (hl),a
    out (0xa1),a
PLY_AKY_SENDPSGREGISTERS_FASTPSGACCESS_A0_A1_REGISTER13_END:
	inc hl
    ld a,#0x6
    out (0xa0),a
    ld a,(hl)
    out (0xa1),a
    ret 
PLY_AKY_RETTABLE_READREGISTERBLOCK:
	.dw PLY_AKY_CHANNEL1_REGISTERBLOCK_RETURN
    .dw PLY_AKY_CHANNEL2_REGISTERBLOCK_RETURN
    .dw PLY_AKY_CHANNEL3_REGISTERBLOCK_RETURN
    .dw PLY_AKY_SENDPSGREGISTERS_FASTPSGACCESS_A0_A1
    .dw PLY_AKY_PSG1AFTERSENDINGPSGREGISTERS
PLY_AKY_CHANNEL1_PTREGISTERBLOCK = 0xf01e
PLY_AKY_CHANNEL1_PTTRACK = 0xf018
PLY_AKY_CHANNEL1_REGISTERBLOCKLINESTATE_OPCODE = 0xf027
PLY_AKY_CHANNEL1_SOUNDEFFECTDATA = 0xf02c
PLY_AKY_CHANNEL1_WAITBEFORENEXTREGISTERBLOCK = 0xf024
PLY_AKY_CHANNEL2_PTREGISTERBLOCK = 0xf020
PLY_AKY_CHANNEL2_PTTRACK = 0xf01a
PLY_AKY_CHANNEL2_REGISTERBLOCKLINESTATE_OPCODE = 0xf028
PLY_AKY_CHANNEL2_SOUNDEFFECTDATA = 0xf034
PLY_AKY_CHANNEL2_WAITBEFORENEXTREGISTERBLOCK = 0xf025
PLY_AKY_CHANNEL3_PTREGISTERBLOCK = 0xf022
PLY_AKY_CHANNEL3_PTTRACK = 0xf01c
PLY_AKY_CHANNEL3_REGISTERBLOCKLINESTATE_OPCODE = 0xf029
PLY_AKY_CHANNEL3_SOUNDEFFECTDATA = 0xf03c
PLY_AKY_CHANNEL3_WAITBEFORENEXTREGISTERBLOCK = 0xf026
PLY_AKY_PATTERNFRAMECOUNTER = 0xf016
PLY_AKY_PSG1HARDWAREREGISTERARRAY = 0xf00b
PLY_AKY_PSG1HARDWAREREGISTERARRAY_END = 0xf010
PLY_AKY_PSG1REGISTER0 = 0xf000
PLY_AKY_PSG1REGISTER2 = 0xf002
PLY_AKY_PSG1REGISTER4 = 0xf004
PLY_AKY_PSG1RETRIG = 0xf00e
PLY_AKY_PTSOUNDEFFECTTABLE = 0xf02a
PLY_AKY_SAVESP = 0xf012
PLY_AKY_SAVESPTEMP = 0xf014
PLY_AKY_SFXHARDWAREPERIOD = 0xf04c
PLY_AKY_SFXPSGREGISTERARRAY = 0xf041
PLY_AKY_SFXREG10 = 0xf04b
PLY_AKY_SFXREG13 = 0xf04e
PLY_AKY_SFXREG23 = 0xf043
PLY_AKY_SFXREG45 = 0xf045
PLY_AKY_SFXREG6 = 0xf050
PLY_AKY_SFXREG8 = 0xf047
PLY_AKY_SFXREG9 = 0xf049
PLY_AKY_SFXRETRIG = 0xf04f
