// Generated by MSXloc 1.0.0
#pragma once
#include "core.h"

// Langage definition
#define LANG_EN 0
#define LANG_FR 1
#define LANG_JA 2
#define LANG_MAX 3

// Text ID definition
#define TEXT_START 0
#define TEXT_OPTIONS 1
#define TEXT_EXIT 2
#define TEXT_MONDAY 3
#define TEXT_TUESDAY 4
#define TEXT_WEDNESDAY 5
#define TEXT_THURSDAY 6
#define TEXT_FRIDAY 7
#define TEXT_SATURDAY 8
#define TEXT_SUNDAY 9
#define TEXT_DATE 10
#define TEXT_YEAR 11
#define TEXT_MAX 12

// Localization data table
const c8* g_LocData[LANG_MAX][TEXT_MAX] =
{
	// EN
	{
		"Start", // TEXT_START
		"Options", // TEXT_OPTIONS
		"Exit", // TEXT_EXIT
		"Monday", // TEXT_MONDAY
		"Tuesday", // TEXT_TUESDAY
		"Wednesday", // TEXT_WEDNESDAY
		"Thursday", // TEXT_THURSDAY
		"Friday", // TEXT_FRIDAY
		"Saturday", // TEXT_SATURDAY
		"Sunday", // TEXT_SUNDAY
		"Date", // TEXT_DATE
		NULL, // TEXT_YEAR
	},
	// FR
	{
		"Commencer", // TEXT_START
		"Options", // TEXT_OPTIONS
		"Quitter", // TEXT_EXIT
		"Lundi", // TEXT_MONDAY
		"Mardi", // TEXT_TUESDAY
		"Mercredi", // TEXT_WEDNESDAY
		"Jeudi", // TEXT_THURSDAY
		"Vendredi", // TEXT_FRIDAY
		"Samedi", // TEXT_SATURDAY
		"Dimanche", // TEXT_SUNDAY
		NULL, // TEXT_DATE
		NULL, // TEXT_YEAR
	},
	// JA
	{
		"スタート", // TEXT_START
		"オプション", // TEXT_OPTIONS
		"しゅうりょう", // TEXT_EXIT
		"げつようび", // TEXT_MONDAY
		"かようび", // TEXT_TUESDAY
		"すいようび", // TEXT_WEDNESDAY
		"もくようび", // TEXT_THURSDAY
		"きんようび", // TEXT_FRIDAY
		"どようび", // TEXT_SATURDAY
		"にちようび", // TEXT_SUNDAY
		NULL, // TEXT_DATE
		"年", // TEXT_YEAR
	},
};