; ____________________________
; ██▀███▀██▀▀▀▀▀▀▀█▀▀█        │   ▄▄       ▄▄   ▄▄
; ██  ▀  █▄  ▀██▄ ▀ ▄█ ▄▀▀ █  │  ██ ▀ ██▄▀ ██▀ █ ██
; █  █ █  ▀▀  ▄█  █  █ ▀▄█ █▄ │  ▀█▄▀ ██   ▀█▄ ▀▄█▀
; ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀────────┘
;  by Guillaume 'Aoineko' Blanchard under CC-BY-AS license
;──────────────────────────────────────────────────────────────────────────────
; crt0 helper defines
;------------------------------------------------------------------------------
; By Guillaume 'Aoineko' Blanchard for MSX Game Library 
; (ɔ) 2022 under CC-BY-AS license
;------------------------------------------------------------------------------
.module	crt0

;------------------------------------------------------------------------------
; Global symbols
.globl _main
.globl l__INITIALIZER
.globl s__INITIALIZED
.globl s__INITIALIZER
.globl s__HEADER
.globl s__GSFINAL
.globl s__HEAP

;------------------------------------------------------------------------------
; I/O ports
PPI_A			= #0xA8
VDP_S			= #0x99
VDP_A			= #0x99
V9_P06			= #0x66

;------------------------------------------------------------------------------
; Main-ROM routines
ENASLT			= #0x0024
ROMVER			= #0x002B
MSXVER			= #0x002D
RSLREG			= #0x0138

;------------------------------------------------------------------------------
; RAM work area variables
HIMEM			= #0xFC4A
EXPTBL			= #0xFCC1
H_STKE			= #0xFEDA
SLTSL			= #0xFFFF

;------------------------------------------------------------------------------
; ROM types
ROM_PLAIN		= 0		; Plain ROM (no mapper)
ROM_MAPPER_8K	= 2		; Mapper 8 KB
ROM_ASCII8		= 2		;  ASCII-8 mapper
ROM_KONAMI		= 3		;  Konami without SCC mapper
ROM_KONAMI_SCC	= 4		;  Konami with SCC mapper
ROM_NEO8		= 5		;  NEO-8 mapper
ROM_YAMANOOTO	= 6		;  Yamanooto mapper
ROM_MAPPER_16K	= 10	; Mapper 16 KB
ROM_ASCII16		= 10	;  ASCII-16 mmaper
ROM_ASCII16X	= 11	;  ASCII16-X mmaper
ROM_NEO16		= 12	;  NEO-16 mapper

;------------------------------------------------------------------------------
; Yamanooto registers types
YAMA_ENAR		= #0x7FFF		; Features enable register
YAMA_ENAR_REGEN	= #0b00000001	; Registers enable. Setting this bit allows writing to all other registers and all register readability.
YAMA_ENAR_WREN	= #0b00010000	; Write enable. Set to 1 to enable writes to flash rom.
YAMA_OFFR		= #0x7FFE		; Mapper offset register
YAMA_CFGR		= #0x7FFD		; Configuration and control register
YAMA_CFGR_MDIS	= #0b00000001	; This bit disables mapping so you avoid mapper changes with small (up to 32 kbyte) roms that poke the switching area. Usually this is a problem only in K4 mode. Remember to reset this bit to make changes again.
YAMA_CFGR_ECHO	= #0b00000010	; This bit allows the built-in PSG to respond to the port number of the internal PSG of the MSX, causing music intended for the internal PSG to be played too in the Yamanooto and be heard through the stereo output of the cartridge. This is set only during boot when you press the HOME key.
YAMA_CFGR_ROMDIS= #0b00000100	; Setting this bit disables access to flash rom. This is automatically set during boot when the DEL key is pressed. You need to clear this bit in software to be able read/write the flash rom.
YAMA_CFGR_K4	= #0b00001000	; Changes mapper configuration from Konami5 (SCC) to Konami4 for compatibility with game compilations including non-SCC games.

;------------------------------------------------------------------------------
; ISR types
ISR_NONE		= 0				; No ISR
ISR_VBLANK		= 1				; V-blank handler (V9938 or V9958)
ISR_VHBLANK		= 2				; V-blank and h-blank handler (V9958)
ISR_V9990		= 3				; V-blank, h-blank and command end handler (V9990)

;------------------------------------------------------------------------------
; Installation in RAM's page 0
RAM0_NONE		= 0				; Don't install anything in RAM 
RAM0_ISR		= 1				; Install only ISR
RAM0_SEGMENT	= 2				; Install ISR and segment data (for mapped-ROM)

;------------------------------------------------------------------------------
; Default values
START_ADDR		= 0x4000		; Program start address
ROM_MAPPER		= ROM_PLAIN		; ROM type
ROM_DELAY		= 0				; Install BDOS
ROM_BCALL		= 0				; Add banked call trampoline
ROM_ISR			= ISR_VBLANK	; ISR type
ROM_RAMISR		= RAM0_NONE		; Install ISR in RAM's page 0
ISR_SET_S0		= 0				; Reset statut register to S#0 in ISR
APP_SIGN		= 0				; Add application signature
APP_SIGN_NAME	= "GL"			; Application creator/group/company name
APP_SIGN_ID		= 0x0000		; Application number
DOS_PARSEARG	= 0				; Parse MSX-DOS command-line arguments
DOS_ISR			= 0				; Install ISR for MSX-DOS

;------------------------------------------------------------------------------
; Project overwrite values; File generated by the build tool
.include "crt0_config.asm"