// ██▀▀█▀▀██▀▀▀▀▀▀▀█▀▀█            ▄▄   ▄▄
// ██  ▀  █▄  ▀██▄ ▀ ▄█  ▄█▄█ ▄▀██ ██▀  ██▄
// █  █ █  ▀▀  ▄█  █  █  ██ █ ▀▄██ ▀█▄▄ ██ █
// ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
//─────────────────────────────────────────────────────────────────────────────
// MSXmath 1.6.1 by Guillaume "Aoineko" Blanchard
// under CC-BY-SA free license
//
// Generated: Mon Nov 27 22:26:15 2023
// Parameters: Entries=32, Bytes=1 (8-bits), Shift=4 (Q4.4)
//─────────────────────────────────────────────────────────────────────────────

// Map table. Range [0:N[
const unsigned char g_Map32[] = {
	0x00, 0x34, 0x67, 0x9B, 0xCE, 0x02, 0x36, 0x69, 
	0x9D, 0xD1, 0x04, 0x38, 0x6B, 0x9F, 0xD3, 0x06, 
	0x3A, 0x6D, 0xA1, 0xD5, 0x08, 0x3C, 0x6F, 0xA3, 
	0xD7, 0x0A, 0x3E, 0x72, 0xA5, 0xD9, 0x0C, 0x40, 
};
