//_____________________________________________________________________________
//   ▄▄   ▄ ▄  ▄▄▄ ▄▄ ▄           ▄▄   ▄▄   
//  ██ ▀ ██▀█ ▀█▄  ▀█▄▀ ▄█▄█ ▄▀██ ██▀  ██▄  
//  ▀█▄▀ ██ █ ▄▄█▀ ██ █ ██ █ ▀▄██ ▀█▄▄ ██ █ 
//_____________________________________________________________________________
// CMSXmath 1.5.1 by Guillaume "Aoineko" Blanchard                              
// under CC-BY-AS free license                                                 
//                                                                             
// Generated: Sat Feb 27 18:45:39 2021
// Parameters: Entries=64, Bytes=2 (16-bits), Shift=8 (Q8.8)               
//_____________________________________________________________________________

// Tangent table. Range [-Pi/2:Pi/2]
static const unsigned short g_Tangent64[65] =
{
	0x0000, 0xF272, 0xF943, 0xFB8C, 0xFCB5, 0xFD69, 0xFDE3, 0xFE3D, 
	0xFE81, 0xFEB8, 0xFEE6, 0xFF0D, 0xFF2E, 0xFF4C, 0xFF67, 0xFF80, 
	0xFF96, 0xFFAC, 0xFFC0, 0xFFD4, 0xFFE7, 0xFFFA, 0x000C, 0x001F, 
	0x0032, 0x0046, 0x005B, 0x0071, 0x0088, 0x00A2, 0x00BD, 0x00DC, 
	0x0100, 0x0128, 0x0159, 0x0194, 0x01DE, 0x0241, 0x02CB, 0x039D, 
	0x0506, 0x081B, 0x145B, 0xD744, 0xF5D9, 0xFA3D, 0xFC02, 0xFCFA, 
	0xFD96, 0xFE04, 0xFE55, 0xFE95, 0xFEC9, 0xFEF4, 0xFF18, 0xFF39, 
	0xFF55, 0xFF6F, 0xFF87, 0xFF9E, 0xFFB3, 0xFFC7, 0xFFDB, 0xFFEE, 
	0x0000, 
};
