; Playing with effects, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Playingwitheffects_Start:
Playingwitheffects_StartDisarkGenerateExternalLabel:

Playingwitheffects_DisarkByteRegionStart0:
	.db 65, 84, 50, 48 ; AT20
Playingwitheffects_DisarkPointerRegionStart1:
	.dw Playingwitheffects_ArpeggioTable	; The address of the Arpeggio table.
	.dw Playingwitheffects_PitchTable	; The address of the Pitch table.
	.dw Playingwitheffects_InstrumentTable	; The address of the Instrument table.
	.dw Playingwitheffects_EffectBlockTable	; The address of the Effect Block table.
Playingwitheffects_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
Playingwitheffects_DisarkPointerRegionStart2:
	.dw Playingwitheffects_Subsong0_Start
Playingwitheffects_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
Playingwitheffects_ArpeggioTable:
Playingwitheffects_DisarkPointerRegionStart3:
	.dw Playingwitheffects_Arpeggio1
	.dw Playingwitheffects_Arpeggio2
	.dw Playingwitheffects_Arpeggio3
	.dw Playingwitheffects_Arpeggio4
	.dw Playingwitheffects_Arpeggio5
	.dw Playingwitheffects_Arpeggio6
	.dw Playingwitheffects_Arpeggio7
	.dw Playingwitheffects_Arpeggio8
	.dw Playingwitheffects_Arpeggio9
Playingwitheffects_DisarkPointerRegionEnd3:

Playingwitheffects_Arpeggio1:
	.db 6	; The speed.

	.db 0
	.db 12
	.db -128
Playingwitheffects_DisarkWordForceReference4:
	.dw Playingwitheffects_Arpeggio1 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio2:
	.db 1	; The speed.

	.db 0
	.db 3
	.db 7
	.db -128
Playingwitheffects_DisarkWordForceReference5:
	.dw Playingwitheffects_Arpeggio2 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio3:
	.db 1	; The speed.

	.db 0
	.db 4
	.db 7
	.db -128
Playingwitheffects_DisarkWordForceReference6:
	.dw Playingwitheffects_Arpeggio3 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio4:
	.db 1	; The speed.

	.db 0
	.db 4
	.db 7
	.db -128
Playingwitheffects_DisarkWordForceReference7:
	.dw Playingwitheffects_Arpeggio4 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio5:
	.db 1	; The speed.

	.db 0
	.db 3
	.db 7
	.db -128
Playingwitheffects_DisarkWordForceReference8:
	.dw Playingwitheffects_Arpeggio5 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio6:
	.db 1	; The speed.

	.db 0
	.db 3
	.db 0
	.db 0
	.db -128
Playingwitheffects_DisarkWordForceReference9:
	.dw Playingwitheffects_Arpeggio6 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio7:
	.db 1	; The speed.

	.db 0
	.db 3
	.db 5
	.db 0
	.db -128
Playingwitheffects_DisarkWordForceReference10:
	.dw Playingwitheffects_Arpeggio7 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio8:
	.db 1	; The speed.

	.db 0
	.db 3
	.db 5
	.db 7
	.db -128
Playingwitheffects_DisarkWordForceReference11:
	.dw Playingwitheffects_Arpeggio8 + 0 + 1	; Loop.

Playingwitheffects_Arpeggio9:
	.db 1	; The speed.

	.db 0
	.db 5
	.db 7
	.db 12
	.db -128
Playingwitheffects_DisarkWordForceReference12:
	.dw Playingwitheffects_Arpeggio9 + 0 + 1	; Loop.

; Declares all the Pitches.
Playingwitheffects_PitchTable:
Playingwitheffects_DisarkPointerRegionStart13:
	.dw Playingwitheffects_Pitch1
	.dw Playingwitheffects_Pitch2
Playingwitheffects_DisarkPointerRegionEnd13:

Playingwitheffects_Pitch1:
	.db 2	; The speed.

	.dw 0
Playingwitheffects_Pitch1_GotoNextForLine0:
Playingwitheffects_DisarkWordForceReference14:
	.dw Playingwitheffects_Pitch1_GotoNextForLine0 + 2
	.dw -1
Playingwitheffects_Pitch1_GotoNextForLine1:
Playingwitheffects_DisarkWordForceReference15:
	.dw Playingwitheffects_Pitch1_GotoNextForLine1 + 2
	.dw -2
Playingwitheffects_Pitch1_GotoNextForLine2:
Playingwitheffects_DisarkWordForceReference16:
	.dw Playingwitheffects_Pitch1_GotoNextForLine2 + 2
	.dw -1
Playingwitheffects_DisarkWordForceReference17:
	.dw Playingwitheffects_Pitch1 + 4 * 0 + 1

Playingwitheffects_Pitch2:
	.db 1	; The speed.

	.dw 16
Playingwitheffects_Pitch2_GotoNextForLine0:
Playingwitheffects_DisarkWordForceReference18:
	.dw Playingwitheffects_Pitch2_GotoNextForLine0 + 2
	.dw 9
Playingwitheffects_Pitch2_GotoNextForLine1:
Playingwitheffects_DisarkWordForceReference19:
	.dw Playingwitheffects_Pitch2_GotoNextForLine1 + 2
	.dw 8
Playingwitheffects_Pitch2_GotoNextForLine2:
Playingwitheffects_DisarkWordForceReference20:
	.dw Playingwitheffects_Pitch2_GotoNextForLine2 + 2
	.dw 7
Playingwitheffects_Pitch2_GotoNextForLine3:
Playingwitheffects_DisarkWordForceReference21:
	.dw Playingwitheffects_Pitch2_GotoNextForLine3 + 2
	.dw 6
Playingwitheffects_Pitch2_GotoNextForLine4:
Playingwitheffects_DisarkWordForceReference22:
	.dw Playingwitheffects_Pitch2_GotoNextForLine4 + 2
	.dw 5
Playingwitheffects_Pitch2_GotoNextForLine5:
Playingwitheffects_DisarkWordForceReference23:
	.dw Playingwitheffects_Pitch2_GotoNextForLine5 + 2
	.dw 4
Playingwitheffects_Pitch2_GotoNextForLine6:
Playingwitheffects_DisarkWordForceReference24:
	.dw Playingwitheffects_Pitch2_GotoNextForLine6 + 2
	.dw 3
Playingwitheffects_Pitch2_GotoNextForLine7:
Playingwitheffects_DisarkWordForceReference25:
	.dw Playingwitheffects_Pitch2_GotoNextForLine7 + 2
	.dw 2
Playingwitheffects_Pitch2_GotoNextForLine8:
Playingwitheffects_DisarkWordForceReference26:
	.dw Playingwitheffects_Pitch2_GotoNextForLine8 + 2
	.dw 1
Playingwitheffects_Pitch2_GotoNextForLine9:
Playingwitheffects_DisarkWordForceReference27:
	.dw Playingwitheffects_Pitch2_GotoNextForLine9 + 2
	.dw 0
Playingwitheffects_DisarkWordForceReference28:
	.dw Playingwitheffects_Pitch2 + 4 * 10 + 1

; Declares all the Instruments.
Playingwitheffects_InstrumentTable:
Playingwitheffects_DisarkPointerRegionStart29:
	.dw Playingwitheffects_EmptyInstrument
	.dw Playingwitheffects_Instrument1
	.dw Playingwitheffects_Instrument2
Playingwitheffects_DisarkPointerRegionEnd29:

Playingwitheffects_EmptyInstrument:
	.db 0	; The speed (>0, 0 for 256).
Playingwitheffects_EmptyInstrument_Loop:	.db 0	; No Soft no Hard. Volume: 0. Noise? false.

	.db 6	; Loop to silence.

Playingwitheffects_Instrument1:
	.db 1	; The speed (>0, 0 for 256).
	.db 249	; Soft only. Volume: 15. Volume only.

	.db 241	; Soft only. Volume: 14. Volume only.

	.db 233	; Soft only. Volume: 13. Volume only.

	.db 225	; Soft only. Volume: 12. Volume only.

	.db 217	; Soft only. Volume: 11. Volume only.

Playingwitheffects_Instrument1_Loop:	.db 209	; Soft only. Volume: 10. Volume only.

	.db 7	; Loop.
Playingwitheffects_DisarkWordForceReference30:
	.dw Playingwitheffects_Instrument1_Loop	; Loop here.

Playingwitheffects_Instrument2:
	.db 2	; The speed (>0, 0 for 256).
	.db 121	; Soft only. Volume: 15.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 241	; Soft only. Volume: 14. Volume only.

	.db 233	; Soft only. Volume: 13. Volume only.

	.db 225	; Soft only. Volume: 12. Volume only.

Playingwitheffects_Instrument2_Loop:	.db 89	; Soft only. Volume: 11.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 209	; Soft only. Volume: 10. Volume only.

	.db 201	; Soft only. Volume: 9. Volume only.

	.db 193	; Soft only. Volume: 8. Volume only.

	.db 185	; Soft only. Volume: 7. Volume only.

	.db 7	; Loop.
Playingwitheffects_DisarkWordForceReference31:
	.dw Playingwitheffects_Instrument2_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
Playingwitheffects_EffectBlockTable:
Playingwitheffects_DisarkPointerRegionStart32:
	.dw Playingwitheffects_EffectBlock_P0	; Index 0
	.dw Playingwitheffects_EffectBlock_P10P0	; Index 1
	.dw Playingwitheffects_EffectBlock_P6P1	; Index 2
	.dw Playingwitheffects_EffectBlock_P15P16P0P32P3	; Index 3
	.dw Playingwitheffects_EffectBlock_P28P53	; Index 4
	.dw Playingwitheffects_EffectBlock_P24P60P0P1	; Index 5
	.dw Playingwitheffects_EffectBlock_P24P62P0P8	; Index 6
	.dw Playingwitheffects_EffectBlock_P7P8P32P4	; Index 7
	.dw Playingwitheffects_EffectBlock_P24P64P0P4	; Index 8
	.dw Playingwitheffects_EffectBlock_P24P48P0P1	; Index 9
	.dw Playingwitheffects_EffectBlock_P7P2P32P3	; Index 10
	.dw Playingwitheffects_EffectBlock_P4P0	; Index 11
	.dw Playingwitheffects_EffectBlock_P24P48P0P2	; Index 12
	.dw Playingwitheffects_EffectBlock_P34P3	; Index 13
	.dw Playingwitheffects_EffectBlock_P5P0P6P3	; Index 14
	.dw Playingwitheffects_EffectBlock_P30P1	; Index 15
	.dw Playingwitheffects_EffectBlock_P32P2	; Index 16
	.dw Playingwitheffects_EffectBlock_P32P8	; Index 17
	.dw Playingwitheffects_EffectBlock_P6P0	; Index 18
	.dw Playingwitheffects_EffectBlock_P6P2	; Index 19
	.dw Playingwitheffects_EffectBlock_P34P2	; Index 20
	.dw Playingwitheffects_EffectBlock_P28P50	; Index 21
	.dw Playingwitheffects_EffectBlock_P28P52	; Index 22
	.dw Playingwitheffects_EffectBlock_P14P48P0	; Index 23
	.dw Playingwitheffects_EffectBlock_P20P48P1	; Index 24
	.dw Playingwitheffects_EffectBlock_P18P16P0	; Index 25
	.dw Playingwitheffects_EffectBlock_P14P16P0	; Index 26
	.dw Playingwitheffects_EffectBlock_P18P48P0	; Index 27
	.dw Playingwitheffects_EffectBlock_P18P0P1	; Index 28
	.dw Playingwitheffects_EffectBlock_P14P208P255	; Index 29
	.dw Playingwitheffects_EffectBlock_P20P32P0	; Index 30
	.dw Playingwitheffects_EffectBlock_P30P11	; Index 31
	.dw Playingwitheffects_EffectBlock_P34P17	; Index 32
	.dw Playingwitheffects_EffectBlock_P2P1	; Index 33
	.dw Playingwitheffects_EffectBlock_P2P2	; Index 34
	.dw Playingwitheffects_EffectBlock_P4P1	; Index 35
	.dw Playingwitheffects_EffectBlock_P4P2	; Index 36
	.dw Playingwitheffects_EffectBlock_P4P3	; Index 37
	.dw Playingwitheffects_EffectBlock_P4P4	; Index 38
	.dw Playingwitheffects_EffectBlock_P4P5	; Index 39
	.dw Playingwitheffects_EffectBlock_P4P6	; Index 40
	.dw Playingwitheffects_EffectBlock_P6P4	; Index 41
	.dw Playingwitheffects_EffectBlock_P6P5	; Index 42
	.dw Playingwitheffects_EffectBlock_P6P6	; Index 43
	.dw Playingwitheffects_EffectBlock_P6P7	; Index 44
	.dw Playingwitheffects_EffectBlock_P10P1	; Index 45
	.dw Playingwitheffects_EffectBlock_P32P4	; Index 46
	.dw Playingwitheffects_EffectBlock_P32P5	; Index 47
	.dw Playingwitheffects_EffectBlock_P30P3	; Index 48
	.dw Playingwitheffects_EffectBlock_P34P1	; Index 49
	.dw Playingwitheffects_EffectBlock_P32P1	; Index 50
	.dw Playingwitheffects_EffectBlock_P2P3	; Index 51
	.dw Playingwitheffects_EffectBlock_P34P5	; Index 52
	.dw Playingwitheffects_EffectBlock_P34P7	; Index 53
	.dw Playingwitheffects_EffectBlock_P4P15	; Index 54
	.dw Playingwitheffects_EffectBlock_P28P48	; Index 55
	.dw Playingwitheffects_EffectBlock_P30P2	; Index 56
	.dw Playingwitheffects_EffectBlock_P32P3	; Index 57
	.dw Playingwitheffects_EffectBlock_P12	; Index 58
	.dw Playingwitheffects_EffectBlock_P22	; Index 59
Playingwitheffects_DisarkPointerRegionEnd32:

Playingwitheffects_EffectBlock_P0:
	.db 0
Playingwitheffects_EffectBlock_P12:
	.db 12
Playingwitheffects_EffectBlock_P22:
	.db 22
Playingwitheffects_EffectBlock_P30P11:
	.db 30, 11
Playingwitheffects_EffectBlock_P34P17:
	.db 34, 17
Playingwitheffects_EffectBlock_P2P1:
	.db 2, 1
Playingwitheffects_EffectBlock_P2P2:
	.db 2, 2
Playingwitheffects_EffectBlock_P2P3:
	.db 2, 3
Playingwitheffects_EffectBlock_P4P0:
	.db 4, 0
Playingwitheffects_EffectBlock_P4P1:
	.db 4, 1
Playingwitheffects_EffectBlock_P4P2:
	.db 4, 2
Playingwitheffects_EffectBlock_P4P3:
	.db 4, 3
Playingwitheffects_EffectBlock_P4P4:
	.db 4, 4
Playingwitheffects_EffectBlock_P4P5:
	.db 4, 5
Playingwitheffects_EffectBlock_P4P6:
	.db 4, 6
Playingwitheffects_EffectBlock_P6P0:
	.db 6, 0
Playingwitheffects_EffectBlock_P6P1:
	.db 6, 1
Playingwitheffects_EffectBlock_P6P2:
	.db 6, 2
Playingwitheffects_EffectBlock_P6P4:
	.db 6, 4
Playingwitheffects_EffectBlock_P6P5:
	.db 6, 5
Playingwitheffects_EffectBlock_P6P6:
	.db 6, 6
Playingwitheffects_EffectBlock_P6P7:
	.db 6, 7
Playingwitheffects_EffectBlock_P24P60P0P1:
	.db 24, 60, 0, 1
Playingwitheffects_EffectBlock_P24P62P0P8:
	.db 24, 62, 0, 8
Playingwitheffects_EffectBlock_P7P8P32P4:
	.db 7, 8, 32, 4
Playingwitheffects_EffectBlock_P24P64P0P4:
	.db 24, 64, 0, 4
Playingwitheffects_EffectBlock_P18P16P0:
	.db 18, 16, 0
Playingwitheffects_EffectBlock_P18P48P0:
	.db 18, 48, 0
Playingwitheffects_EffectBlock_P24P48P0P1:
	.db 24, 48, 0, 1
Playingwitheffects_EffectBlock_P24P48P0P2:
	.db 24, 48, 0, 2
Playingwitheffects_EffectBlock_P7P2P32P3:
	.db 7, 2, 32, 3
Playingwitheffects_EffectBlock_P14P16P0:
	.db 14, 16, 0
Playingwitheffects_EffectBlock_P14P48P0:
	.db 14, 48, 0
Playingwitheffects_EffectBlock_P18P0P1:
	.db 18, 0, 1
Playingwitheffects_EffectBlock_P14P208P255:
	.db 14, 208, 255
Playingwitheffects_EffectBlock_P20P32P0:
	.db 20, 32, 0
Playingwitheffects_EffectBlock_P20P48P1:
	.db 20, 48, 1
Playingwitheffects_EffectBlock_P5P0P6P3:
	.db 5, 0, 6, 3
Playingwitheffects_EffectBlock_P15P16P0P32P3:
	.db 15, 16, 0, 32, 3
Playingwitheffects_EffectBlock_P10P0:
	.db 10, 0
Playingwitheffects_EffectBlock_P10P1:
	.db 10, 1
Playingwitheffects_EffectBlock_P30P1:
	.db 30, 1
Playingwitheffects_EffectBlock_P30P2:
	.db 30, 2
Playingwitheffects_EffectBlock_P30P3:
	.db 30, 3
Playingwitheffects_EffectBlock_P32P1:
	.db 32, 1
Playingwitheffects_EffectBlock_P32P2:
	.db 32, 2
Playingwitheffects_EffectBlock_P32P3:
	.db 32, 3
Playingwitheffects_EffectBlock_P32P4:
	.db 32, 4
Playingwitheffects_EffectBlock_P32P5:
	.db 32, 5
Playingwitheffects_EffectBlock_P32P8:
	.db 32, 8
Playingwitheffects_EffectBlock_P34P1:
	.db 34, 1
Playingwitheffects_EffectBlock_P34P2:
	.db 34, 2
Playingwitheffects_EffectBlock_P34P3:
	.db 34, 3
Playingwitheffects_EffectBlock_P34P5:
	.db 34, 5
Playingwitheffects_EffectBlock_P34P7:
	.db 34, 7
Playingwitheffects_EffectBlock_P4P15:
	.db 4, 15
Playingwitheffects_EffectBlock_P28P48:
	.db 28, 48
Playingwitheffects_EffectBlock_P28P50:
	.db 28, 50
Playingwitheffects_EffectBlock_P28P52:
	.db 28, 52
Playingwitheffects_EffectBlock_P28P53:
	.db 28, 53

Playingwitheffects_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
Playingwitheffects_Subsong0_DisarkByteRegionStart0:
Playingwitheffects_Subsong0_Start:
	.db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.db 0	; Digichannel (0-2).
	.db 1	; PSG count (>0).
	.db 0	; Loop start index (>=0).
	.db 6	; End index (>=0).
	.db 6	; Initial speed (>=0).
	.db 12	; Base note index (>=0).

Playingwitheffects_Subsong0_Linker:
Playingwitheffects_Subsong0_DisarkPointerRegionStart1:
; Position 0
Playingwitheffects_Subsong0_Linker_Loop:
	.dw Playingwitheffects_Subsong0_Track0
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock0

; Position 1
	.dw Playingwitheffects_Subsong0_Track3
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock1

; Position 2
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track4
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock2

; Position 3
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track2
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock3

; Position 4
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track5
	.dw Playingwitheffects_Subsong0_LinkerBlock4

; Position 5
	.dw Playingwitheffects_Subsong0_Track6
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock5

; Position 6
	.dw Playingwitheffects_Subsong0_Track7
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_Track1
	.dw Playingwitheffects_Subsong0_LinkerBlock6

Playingwitheffects_Subsong0_DisarkPointerRegionEnd1:
	.dw 0	; Loop.
Playingwitheffects_Subsong0_DisarkWordForceReference2:
	.dw Playingwitheffects_Subsong0_Linker_Loop

Playingwitheffects_Subsong0_LinkerBlock0:
	.db 38	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference3:
	.dw Playingwitheffects_Subsong0_SpeedTrack0	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference4:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock1:
	.db 48	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference5:
	.dw Playingwitheffects_Subsong0_SpeedTrack1	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference6:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock2:
	.db 80	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference7:
	.dw Playingwitheffects_Subsong0_SpeedTrack2	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference8:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock3:
	.db 68	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference9:
	.dw Playingwitheffects_Subsong0_SpeedTrack3	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference10:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock4:
	.db 80	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference11:
	.dw Playingwitheffects_Subsong0_SpeedTrack0	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference12:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock5:
	.db 64	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference13:
	.dw Playingwitheffects_Subsong0_SpeedTrack1	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference14:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.
Playingwitheffects_Subsong0_LinkerBlock6:
	.db 26	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Playingwitheffects_Subsong0_DisarkWordForceReference15:
	.dw Playingwitheffects_Subsong0_SpeedTrack0	; SpeedTrack address.
Playingwitheffects_Subsong0_DisarkWordForceReference16:
	.dw Playingwitheffects_Subsong0_EventTrack0	; EventTrack address.

Playingwitheffects_Subsong0_Track0:
	.db 152
	.db 1	; New Instrument (1).
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 28	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 124	; No note, but effects.
	.db 25	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 124	; No note, but effects.
	.db 24	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 59	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 6	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 8	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 5	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 12	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track1:
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track2:
	.db 228
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 18	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 47	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 46	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 50	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 19	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 10	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 228
	.db 2	; New Instrument (2).
	.db 0	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 100
	.db 2	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 100
	.db 19	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 100
	.db 18	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 17	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 3	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track3:
	.db 240
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 35	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 36	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 37	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 38	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 39	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 11	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 40	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 11	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 54	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 29	; Index to an effect block.
	.db 61, 15	; Waits for 16 lines.

	.db 124	; No note, but effects.
	.db 23	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track4:
	.db 228
	.db 1	; New Instrument (1).
	.db 14	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 36
	.db 36
	.db 60	; Waits for 1 line.

	.db 36
	.db 60	; Waits for 1 line.

	.db 36
	.db 36
	.db 60	; Waits for 1 line.

	.db 38
	.db 60	; Waits for 1 line.

	.db 104
	.db 41	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 104
	.db 16	; Index to an effect block.
	.db 61, 5	; Waits for 6 lines.

	.db 124	; No note, but effects.
	.db 57	; Index to an effect block.
	.db 61, 5	; Waits for 6 lines.

	.db 124	; No note, but effects.
	.db 17	; Index to an effect block.
	.db 61, 8	; Waits for 9 lines.

	.db 100
	.db 42	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 124	; No note, but effects.
	.db 43	; Index to an effect block.
	.db 62 + 2 * 64	; Optimized wait for 4 lines.

	.db 124	; No note, but effects.
	.db 44	; Index to an effect block.
	.db 61, 5	; Waits for 6 lines.

	.db 124	; No note, but effects.
	.db 7	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 124	; No note, but effects.
	.db 26	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track5:
	.db 240
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 58	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 13	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 52	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 32	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 49	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 20	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 112
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 45	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 50
	.db 60	; Waits for 1 line.

	.db 52
	.db 60	; Waits for 1 line.

	.db 53
	.db 60	; Waits for 1 line.

	.db 55
	.db 60	; Waits for 1 line.

	.db 119
	.db 20	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 119
	.db 13	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 119
	.db 53	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 112
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 27	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 30	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 58	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 9	; Index to an effect block.
	.db 61, 6	; Waits for 7 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track6:
	.db 228
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 100
	.db 33	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 100
	.db 34	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 100
	.db 51	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 100
	.db 0	; Index to an effect block.
	.db 61, 6	; Waits for 7 lines.

	.db 36
	.db 60	; Waits for 1 line.

	.db 38
	.db 60	; Waits for 1 line.

	.db 40
	.db 60	; Waits for 1 line.

	.db 41
	.db 60	; Waits for 1 line.

	.db 43
	.db 60	; Waits for 1 line.

	.db 41
	.db 60	; Waits for 1 line.

	.db 40
	.db 60	; Waits for 1 line.

	.db 38
	.db 60	; Waits for 1 line.

	.db 36
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 36
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 21	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 43
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 21	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 55	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Playingwitheffects_Subsong0_Track7:
	.db 228
	.db 2	; New Instrument (2).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 100
	.db 15	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 100
	.db 48	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 56	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 15	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 31	; Index to an effect block.
	.db 61, 5	; Waits for 6 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


; The speed tracks
Playingwitheffects_Subsong0_SpeedTrack0:
	.db 64	; Value: 32.
	.db 253	; Wait for 127 lines.
Playingwitheffects_Subsong0_SpeedTrack1:
	.db 12	; Value: 6.
	.db 253	; Wait for 127 lines.
Playingwitheffects_Subsong0_SpeedTrack2:
	.db 14	; Value: 7.
	.db 29	; Wait for 15 lines.
	.db 18	; Value: 9.
	.db 221	; Wait for 111 lines.
Playingwitheffects_Subsong0_SpeedTrack3:
	.db 48	; Value: 24.
	.db 113	; Wait for 57 lines.
	.db 96	; Value: 48.
	.db 137	; Wait for 69 lines.

; The event tracks
Playingwitheffects_Subsong0_EventTrack0:
	.db 255	; Wait for 128 lines.

Playingwitheffects_Subsong0_DisarkByteRegionEnd0:
