; Just add cream, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Justaddcream_Start:
Justaddcream_StartDisarkGenerateExternalLabel:

Justaddcream_DisarkByteRegionStart0:
	.db 65, 84, 50, 48 ; AT20
Justaddcream_DisarkPointerRegionStart1:
	.dw Justaddcream_ArpeggioTable	; The address of the Arpeggio table.
	.dw Justaddcream_PitchTable	; The address of the Pitch table.
	.dw Justaddcream_InstrumentTable	; The address of the Instrument table.
	.dw Justaddcream_EffectBlockTable	; The address of the Effect Block table.
Justaddcream_DisarkPointerRegionEnd1:


; The addresses of each Subsong:
Justaddcream_DisarkPointerRegionStart2:
	.dw Justaddcream_Subsong0_Start
Justaddcream_DisarkPointerRegionEnd2:

; Declares all the Arpeggios.
Justaddcream_ArpeggioTable:
Justaddcream_DisarkPointerRegionStart3:
	.dw Justaddcream_Arpeggio1
	.dw Justaddcream_Arpeggio2
	.dw Justaddcream_Arpeggio3
Justaddcream_DisarkPointerRegionEnd3:

Justaddcream_Arpeggio1:
	.db 2	; The speed.

	.db 7
	.db 4
	.db 0
	.db -128
Justaddcream_DisarkWordForceReference4:
	.dw Justaddcream_Arpeggio1 + 0 + 1	; Loop.

Justaddcream_Arpeggio2:
	.db 2	; The speed.

	.db 16
	.db 12
	.db 7
	.db -128
Justaddcream_DisarkWordForceReference5:
	.dw Justaddcream_Arpeggio2 + 0 + 1	; Loop.

Justaddcream_Arpeggio3:
	.db 2	; The speed.

	.db 12
	.db 7
	.db 4
	.db -128
Justaddcream_DisarkWordForceReference6:
	.dw Justaddcream_Arpeggio3 + 0 + 1	; Loop.

; Declares all the Pitches.
Justaddcream_PitchTable:
Justaddcream_DisarkPointerRegionStart7:
	.dw Justaddcream_Pitch1
Justaddcream_DisarkPointerRegionEnd7:

Justaddcream_Pitch1:
	.db 1	; The speed.

	.dw -1
Justaddcream_Pitch1_GotoNextForLine0:
Justaddcream_DisarkWordForceReference8:
	.dw Justaddcream_Pitch1_GotoNextForLine0 + 2
	.dw -2
Justaddcream_Pitch1_GotoNextForLine1:
Justaddcream_DisarkWordForceReference9:
	.dw Justaddcream_Pitch1_GotoNextForLine1 + 2
	.dw -3
Justaddcream_Pitch1_GotoNextForLine2:
Justaddcream_DisarkWordForceReference10:
	.dw Justaddcream_Pitch1_GotoNextForLine2 + 2
	.dw -2
Justaddcream_Pitch1_GotoNextForLine3:
Justaddcream_DisarkWordForceReference11:
	.dw Justaddcream_Pitch1_GotoNextForLine3 + 2
	.dw -1
Justaddcream_Pitch1_GotoNextForLine4:
Justaddcream_DisarkWordForceReference12:
	.dw Justaddcream_Pitch1_GotoNextForLine4 + 2
	.dw 1
Justaddcream_Pitch1_GotoNextForLine5:
Justaddcream_DisarkWordForceReference13:
	.dw Justaddcream_Pitch1_GotoNextForLine5 + 2
	.dw 2
Justaddcream_Pitch1_GotoNextForLine6:
Justaddcream_DisarkWordForceReference14:
	.dw Justaddcream_Pitch1_GotoNextForLine6 + 2
	.dw 3
Justaddcream_Pitch1_GotoNextForLine7:
Justaddcream_DisarkWordForceReference15:
	.dw Justaddcream_Pitch1_GotoNextForLine7 + 2
	.dw 2
Justaddcream_DisarkWordForceReference16:
	.dw Justaddcream_Pitch1 + 4 * 0 + 1

; Declares all the Instruments.
Justaddcream_InstrumentTable:
Justaddcream_DisarkPointerRegionStart17:
	.dw Justaddcream_EmptyInstrument
	.dw Justaddcream_Instrument1
	.dw Justaddcream_Instrument2
	.dw Justaddcream_Instrument3
	.dw Justaddcream_Instrument4
	.dw Justaddcream_Instrument5
	.dw Justaddcream_Instrument6
	.dw Justaddcream_Instrument7
	.dw Justaddcream_Instrument8
	.dw Justaddcream_Instrument9
	.dw Justaddcream_Instrument10
	.dw Justaddcream_Instrument11
Justaddcream_DisarkPointerRegionEnd17:

Justaddcream_EmptyInstrument:
	.db 0	; The speed (>0, 0 for 256).
Justaddcream_EmptyInstrument_Loop:	.db 0	; No Soft no Hard. Volume: 0. Noise? false.

	.db 6	; Loop to silence.

Justaddcream_Instrument1:
	.db 1	; The speed (>0, 0 for 256).
	.db 105	; Soft only. Volume: 13.
	.db 159	; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
	.dw 956	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1012	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1276	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1517	; Forced period.

	.db 105	; Soft only. Volume: 13.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 2408	; Forced period.

	.db 6	; Loop to silence.

Justaddcream_Instrument2:
	.db 1	; The speed (>0, 0 for 256).
	.db 121	; Soft only. Volume: 15.
	.db 145	; Additional data. Noise: 17. Pitch? false. Arp? false. Period? true.
	.dw 426	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 536	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 638	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 716	; Forced period.

	.db 232	; No Soft no Hard. Volume: 13. Noise? true.
	.db 13	; Noise: 13.

	.db 216	; No Soft no Hard. Volume: 11. Noise? true.
	.db 13	; Noise: 13.

	.db 6	; Loop to silence.

Justaddcream_Instrument3:
	.db 1	; The speed (>0, 0 for 256).
	.db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.db 130	; Simple case. Ratio: 5

	.db 2	; Soft to Hard. Envelope: 8. Retrig ? false. Noise ? false.
	.db 130	; Simple case. Ratio: 5

	.db 233	; Soft only. Volume: 13. Volume only.

	.db 225	; Soft only. Volume: 12. Volume only.

	.db 217	; Soft only. Volume: 11. Volume only.

	.db 217	; Soft only. Volume: 11. Volume only.

Justaddcream_Instrument3_Loop:	.db 217	; Soft only. Volume: 11. Volume only.

	.db 217	; Soft only. Volume: 11. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference18:
	.dw Justaddcream_Instrument3_Loop	; Loop here.

Justaddcream_Instrument4:
	.db 1	; The speed (>0, 0 for 256).
	.db 225	; Soft only. Volume: 12. Volume only.

	.db 217	; Soft only. Volume: 11. Volume only.

	.db 209	; Soft only. Volume: 10. Volume only.

Justaddcream_Instrument4_Loop:	.db 201	; Soft only. Volume: 9. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference19:
	.dw Justaddcream_Instrument4_Loop	; Loop here.

Justaddcream_Instrument5:
	.db 1	; The speed (>0, 0 for 256).
	.db 105	; Soft only. Volume: 13.
	.db 159	; Additional data. Noise: 31. Pitch? false. Arp? false. Period? true.
	.dw 956	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1012	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1276	; Forced period.

	.db 121	; Soft only. Volume: 15.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 1517	; Forced period.

Justaddcream_Instrument5_Loop:	.db 217	; Soft only. Volume: 11. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference20:
	.dw Justaddcream_Instrument5_Loop	; Loop here.

Justaddcream_Instrument6:
	.db 1	; The speed (>0, 0 for 256).
	.db 113	; Soft only. Volume: 14.
	.db 145	; Additional data. Noise: 17. Pitch? false. Arp? false. Period? true.
	.dw 426	; Forced period.

	.db 113	; Soft only. Volume: 14.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 536	; Forced period.

	.db 113	; Soft only. Volume: 14.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 638	; Forced period.

	.db 113	; Soft only. Volume: 14.
	.db 128	; Additional data. Noise: 0. Pitch? false. Arp? false. Period? true.
	.dw 716	; Forced period.

	.db 224	; No Soft no Hard. Volume: 12. Noise? true.
	.db 13	; Noise: 13.

Justaddcream_Instrument6_Loop:	.db 217	; Soft only. Volume: 11. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference21:
	.dw Justaddcream_Instrument6_Loop	; Loop here.

Justaddcream_Instrument7:
	.db 1	; The speed (>0, 0 for 256).
	.db 241	; Soft only. Volume: 14. Volume only.

	.db 233	; Soft only. Volume: 13. Volume only.

	.db 225	; Soft only. Volume: 12. Volume only.

Justaddcream_Instrument7_Loop:	.db 217	; Soft only. Volume: 11. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference22:
	.dw Justaddcream_Instrument7_Loop	; Loop here.

Justaddcream_Instrument8:
	.db 1	; The speed (>0, 0 for 256).
Justaddcream_Instrument8_Loop:	.db 193	; Soft only. Volume: 8. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference23:
	.dw Justaddcream_Instrument8_Loop	; Loop here.

Justaddcream_Instrument9:
	.db 1	; The speed (>0, 0 for 256).
	.db 73	; Soft only. Volume: 9.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 65	; Soft only. Volume: 8.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 185	; Soft only. Volume: 7. Volume only.

Justaddcream_Instrument9_Loop:	.db 177	; Soft only. Volume: 6. Volume only.

	.db 49	; Soft only. Volume: 6.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 49	; Soft only. Volume: 6.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 177	; Soft only. Volume: 6. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference24:
	.dw Justaddcream_Instrument9_Loop	; Loop here.

Justaddcream_Instrument10:
	.db 1	; The speed (>0, 0 for 256).
	.db 49	; Soft only. Volume: 6.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 41	; Soft only. Volume: 5.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 161	; Soft only. Volume: 4. Volume only.

Justaddcream_Instrument10_Loop:	.db 153	; Soft only. Volume: 3. Volume only.

	.db 25	; Soft only. Volume: 3.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 25	; Soft only. Volume: 3.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 153	; Soft only. Volume: 3. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference25:
	.dw Justaddcream_Instrument10_Loop	; Loop here.

Justaddcream_Instrument11:
	.db 1	; The speed (>0, 0 for 256).
	.db 41	; Soft only. Volume: 5.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 33	; Soft only. Volume: 4.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 153	; Soft only. Volume: 3. Volume only.

Justaddcream_Instrument11_Loop:	.db 145	; Soft only. Volume: 2. Volume only.

	.db 17	; Soft only. Volume: 2.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 17	; Soft only. Volume: 2.
	.db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	.db 12	; Arpeggio.

	.db 145	; Soft only. Volume: 2. Volume only.

	.db 7	; Loop.
Justaddcream_DisarkWordForceReference26:
	.dw Justaddcream_Instrument11_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
Justaddcream_EffectBlockTable:
Justaddcream_DisarkPointerRegionStart27:
	.dw Justaddcream_EffectBlock_P4P0	; Index 0
	.dw Justaddcream_EffectBlock_P14P64P0	; Index 1
	.dw Justaddcream_EffectBlock_P4P1	; Index 2
	.dw Justaddcream_EffectBlock_P5P0P14P64P0	; Index 3
	.dw Justaddcream_EffectBlock_P5P0P6P2	; Index 4
	.dw Justaddcream_EffectBlock_P5P0P10P0	; Index 5
	.dw Justaddcream_EffectBlock_P15P112P0P12	; Index 6
	.dw Justaddcream_EffectBlock_P5P0P6P1	; Index 7
	.dw Justaddcream_EffectBlock_P5P0P6P0	; Index 8
	.dw Justaddcream_EffectBlock_P15P64P0P6P1	; Index 9
	.dw Justaddcream_EffectBlock_P6P1	; Index 10
	.dw Justaddcream_EffectBlock_P5P0P14P112P0	; Index 11
	.dw Justaddcream_EffectBlock_P5P0P14P160P0	; Index 12
	.dw Justaddcream_EffectBlock_P5P0P15P64P0P6P0	; Index 13
	.dw Justaddcream_EffectBlock_P5P0P15P64P0P6P2	; Index 14
	.dw Justaddcream_EffectBlock_P14P160P0	; Index 15
	.dw Justaddcream_EffectBlock_P10P0	; Index 16
	.dw Justaddcream_EffectBlock_P15P64P0P6P0	; Index 17
	.dw Justaddcream_EffectBlock_P5P0P13P18P0P1	; Index 18
	.dw Justaddcream_EffectBlock_P20P0P5	; Index 19
	.dw Justaddcream_EffectBlock_P5P0P15P112P0P12	; Index 20
	.dw Justaddcream_EffectBlock_P5P0P18P0P2	; Index 21
	.dw Justaddcream_EffectBlock_P4P2	; Index 22
	.dw Justaddcream_EffectBlock_P15P64P0P20P0P16	; Index 23
	.dw Justaddcream_EffectBlock_P24P64P0P1	; Index 24
	.dw Justaddcream_EffectBlock_P24P60P0P2	; Index 25
	.dw Justaddcream_EffectBlock_P15P64P0P6P2	; Index 26
	.dw Justaddcream_EffectBlock_P6P2	; Index 27
	.dw Justaddcream_EffectBlock_P5P14P15P128P255P13P6P1	; Index 28
	.dw Justaddcream_EffectBlock_P6P0	; Index 29
	.dw Justaddcream_EffectBlock_P24P59P128P1	; Index 30
	.dw Justaddcream_EffectBlock_P13P18P128P1	; Index 31
	.dw Justaddcream_EffectBlock_P24P57P0P3	; Index 32
	.dw Justaddcream_EffectBlock_P15P8P0P20P0P6	; Index 33
	.dw Justaddcream_EffectBlock_P5P0P8	; Index 34
	.dw Justaddcream_EffectBlock_P5P0P18P0P12	; Index 35
	.dw Justaddcream_EffectBlock_P5P0P18P128P1	; Index 36
	.dw Justaddcream_EffectBlock_P4P3	; Index 37
	.dw Justaddcream_EffectBlock_P24P23P0P12	; Index 38
	.dw Justaddcream_EffectBlock_P24P48P128P1	; Index 39
	.dw Justaddcream_EffectBlock_P5P0P13P8	; Index 40
	.dw Justaddcream_EffectBlock_P14P32P0	; Index 41
	.dw Justaddcream_EffectBlock_P14P8P0	; Index 42
	.dw Justaddcream_EffectBlock_P14P112P0	; Index 43
	.dw Justaddcream_EffectBlock_P12	; Index 44
	.dw Justaddcream_EffectBlock_P20P0P1	; Index 45
	.dw Justaddcream_EffectBlock_P4P4	; Index 46
	.dw Justaddcream_EffectBlock_P4P5	; Index 47
Justaddcream_DisarkPointerRegionEnd27:

Justaddcream_EffectBlock_P12:
	.db 12
Justaddcream_EffectBlock_P4P0:
	.db 4, 0
Justaddcream_EffectBlock_P4P1:
	.db 4, 1
Justaddcream_EffectBlock_P4P2:
	.db 4, 2
Justaddcream_EffectBlock_P4P3:
	.db 4, 3
Justaddcream_EffectBlock_P4P4:
	.db 4, 4
Justaddcream_EffectBlock_P4P5:
	.db 4, 5
Justaddcream_EffectBlock_P6P0:
	.db 6, 0
Justaddcream_EffectBlock_P6P1:
	.db 6, 1
Justaddcream_EffectBlock_P6P2:
	.db 6, 2
Justaddcream_EffectBlock_P5P0P8:
	.db 5, 0, 8
Justaddcream_EffectBlock_P24P60P0P2:
	.db 24, 60, 0, 2
Justaddcream_EffectBlock_P5P14P15P128P255P13P6P1:
	.db 5, 14, 15, 128, 255, 13, 6, 1
Justaddcream_EffectBlock_P24P64P0P1:
	.db 24, 64, 0, 1
Justaddcream_EffectBlock_P14P112P0:
	.db 14, 112, 0
Justaddcream_EffectBlock_P14P160P0:
	.db 14, 160, 0
Justaddcream_EffectBlock_P15P8P0P20P0P6:
	.db 15, 8, 0, 20, 0, 6
Justaddcream_EffectBlock_P5P0P15P112P0P12:
	.db 5, 0, 15, 112, 0, 12
Justaddcream_EffectBlock_P5P0P18P0P2:
	.db 5, 0, 18, 0, 2
Justaddcream_EffectBlock_P15P64P0P20P0P16:
	.db 15, 64, 0, 20, 0, 16
Justaddcream_EffectBlock_P5P0P14P112P0:
	.db 5, 0, 14, 112, 0
Justaddcream_EffectBlock_P5P0P14P160P0:
	.db 5, 0, 14, 160, 0
Justaddcream_EffectBlock_P5P0P10P0:
	.db 5, 0, 10, 0
Justaddcream_EffectBlock_P5P0P13P8:
	.db 5, 0, 13, 8
Justaddcream_EffectBlock_P5P0P15P64P0P6P0:
	.db 5, 0, 15, 64, 0, 6, 0
Justaddcream_EffectBlock_P5P0P15P64P0P6P2:
	.db 5, 0, 15, 64, 0, 6, 2
Justaddcream_EffectBlock_P24P59P128P1:
	.db 24, 59, 128, 1
Justaddcream_EffectBlock_P14P32P0:
	.db 14, 32, 0
Justaddcream_EffectBlock_P14P64P0:
	.db 14, 64, 0
Justaddcream_EffectBlock_P13P18P128P1:
	.db 13, 18, 128, 1
Justaddcream_EffectBlock_P5P0P13P18P0P1:
	.db 5, 0, 13, 18, 0, 1
Justaddcream_EffectBlock_P14P8P0:
	.db 14, 8, 0
Justaddcream_EffectBlock_P24P23P0P12:
	.db 24, 23, 0, 12
Justaddcream_EffectBlock_P24P48P128P1:
	.db 24, 48, 128, 1
Justaddcream_EffectBlock_P5P0P18P0P12:
	.db 5, 0, 18, 0, 12
Justaddcream_EffectBlock_P15P112P0P12:
	.db 15, 112, 0, 12
Justaddcream_EffectBlock_P24P57P0P3:
	.db 24, 57, 0, 3
Justaddcream_EffectBlock_P15P64P0P6P0:
	.db 15, 64, 0, 6, 0
Justaddcream_EffectBlock_P15P64P0P6P1:
	.db 15, 64, 0, 6, 1
Justaddcream_EffectBlock_P15P64P0P6P2:
	.db 15, 64, 0, 6, 2
Justaddcream_EffectBlock_P5P0P6P0:
	.db 5, 0, 6, 0
Justaddcream_EffectBlock_P5P0P6P1:
	.db 5, 0, 6, 1
Justaddcream_EffectBlock_P5P0P6P2:
	.db 5, 0, 6, 2
Justaddcream_EffectBlock_P5P0P14P64P0:
	.db 5, 0, 14, 64, 0
Justaddcream_EffectBlock_P20P0P1:
	.db 20, 0, 1
Justaddcream_EffectBlock_P20P0P5:
	.db 20, 0, 5
Justaddcream_EffectBlock_P10P0:
	.db 10, 0
Justaddcream_EffectBlock_P5P0P18P128P1:
	.db 5, 0, 18, 128, 1

Justaddcream_DisarkByteRegionEnd0:

; Subsong 0
; ----------------------
Justaddcream_Subsong0_DisarkByteRegionStart0:
Justaddcream_Subsong0_Start:
	.db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	.db 0	; Digichannel (0-2).
	.db 1	; PSG count (>0).
	.db 4	; Loop start index (>=0).
	.db 27	; End index (>=0).
	.db 6	; Initial speed (>=0).
	.db 9	; Base note index (>=0).

Justaddcream_Subsong0_Linker:
Justaddcream_Subsong0_DisarkPointerRegionStart1:
; Position 0
	.dw Justaddcream_Subsong0_Track17
	.dw Justaddcream_Subsong0_Track22
	.dw Justaddcream_Subsong0_Track0
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 1
	.dw Justaddcream_Subsong0_Track18
	.dw Justaddcream_Subsong0_Track21
	.dw Justaddcream_Subsong0_Track0
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 2
	.dw Justaddcream_Subsong0_Track2
	.dw Justaddcream_Subsong0_Track19
	.dw Justaddcream_Subsong0_Track20
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 3
	.dw Justaddcream_Subsong0_Track2
	.dw Justaddcream_Subsong0_Track0
	.dw Justaddcream_Subsong0_Track29
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 4
Justaddcream_Subsong0_Linker_Loop:
	.dw Justaddcream_Subsong0_Track2
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track1
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 5
	.dw Justaddcream_Subsong0_Track24
	.dw Justaddcream_Subsong0_Track25
	.dw Justaddcream_Subsong0_Track26
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 6
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track5
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 7
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track23
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 8
	.dw Justaddcream_Subsong0_Track9
	.dw Justaddcream_Subsong0_Track7
	.dw Justaddcream_Subsong0_Track30
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 9
	.dw Justaddcream_Subsong0_Track10
	.dw Justaddcream_Subsong0_Track8
	.dw Justaddcream_Subsong0_Track30
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 10
	.dw Justaddcream_Subsong0_Track11
	.dw Justaddcream_Subsong0_Track7
	.dw Justaddcream_Subsong0_Track30
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 11
	.dw Justaddcream_Subsong0_Track12
	.dw Justaddcream_Subsong0_Track8
	.dw Justaddcream_Subsong0_Track0
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 12
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track5
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 13
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track6
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 14
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track5
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 15
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track23
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 16
	.dw Justaddcream_Subsong0_Track9
	.dw Justaddcream_Subsong0_Track7
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 17
	.dw Justaddcream_Subsong0_Track10
	.dw Justaddcream_Subsong0_Track8
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 18
	.dw Justaddcream_Subsong0_Track11
	.dw Justaddcream_Subsong0_Track7
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 19
	.dw Justaddcream_Subsong0_Track12
	.dw Justaddcream_Subsong0_Track8
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 20
	.dw Justaddcream_Subsong0_Track13
	.dw Justaddcream_Subsong0_Track28
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 21
	.dw Justaddcream_Subsong0_Track14
	.dw Justaddcream_Subsong0_Track28
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 22
	.dw Justaddcream_Subsong0_Track15
	.dw Justaddcream_Subsong0_Track28
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 23
	.dw Justaddcream_Subsong0_Track16
	.dw Justaddcream_Subsong0_Track28
	.dw Justaddcream_Subsong0_Track27
	.dw Justaddcream_Subsong0_LinkerBlock1

; Position 24
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track5
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 25
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track6
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 26
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track5
	.dw Justaddcream_Subsong0_LinkerBlock0

; Position 27
	.dw Justaddcream_Subsong0_Track4
	.dw Justaddcream_Subsong0_Track3
	.dw Justaddcream_Subsong0_Track23
	.dw Justaddcream_Subsong0_LinkerBlock0

Justaddcream_Subsong0_DisarkPointerRegionEnd1:
	.dw 0	; Loop.
Justaddcream_Subsong0_DisarkWordForceReference2:
	.dw Justaddcream_Subsong0_Linker_Loop

Justaddcream_Subsong0_LinkerBlock0:
	.db 64	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Justaddcream_Subsong0_DisarkWordForceReference3:
	.dw Justaddcream_Subsong0_SpeedTrack0	; SpeedTrack address.
Justaddcream_Subsong0_DisarkWordForceReference4:
	.dw Justaddcream_Subsong0_EventTrack0	; EventTrack address.
Justaddcream_Subsong0_LinkerBlock1:
	.db 32	; Height.
	.db 0	; Transposition 0.
	.db 0	; Transposition 1.
	.db 0	; Transposition 2.
Justaddcream_Subsong0_DisarkWordForceReference5:
	.dw Justaddcream_Subsong0_SpeedTrack0	; SpeedTrack address.
Justaddcream_Subsong0_DisarkWordForceReference6:
	.dw Justaddcream_Subsong0_EventTrack0	; EventTrack address.

Justaddcream_Subsong0_Track0:
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track1:
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 3
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track2:
	.db 204
	.db 3	; New Instrument (3).
	.db 34	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 3	; New Instrument (3).
	.db 10
	.db 12
	.db 60	; Waits for 1 line.

	.db 15
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 17
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 133
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 145
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 17
	.db 15
	.db 17
	.db 60	; Waits for 1 line.

	.db 19
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 148
	.db 3	; New Instrument (3).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 136
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 148
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 20
	.db 15
	.db 20
	.db 60	; Waits for 1 line.

	.db 22
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 143
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 138
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 143
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 22
	.db 10
	.db 14
	.db 60	; Waits for 1 line.

	.db 17
	.db 128
	.db 0	; New Instrument (0).
	.db 142
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 10
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track3:
	.db 231
	.db 4	; New Instrument (4).
	.db 8	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 13	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 17	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 14	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 8	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 108
	.db 27	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 46
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 108
	.db 7	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 115
	.db 29	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 115
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 110
	.db 8	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 26	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track4:
	.db 204
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 6	; New Instrument (6).
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 3	; New Instrument (3).
	.db 10
	.db 140
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 143
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 145
	.db 5	; New Instrument (5).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 133
	.db 5	; New Instrument (5).
	.db 128
	.db 0	; New Instrument (0).
	.db 145
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 145
	.db 3	; New Instrument (3).
	.db 15
	.db 145
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 147
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 212
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 20
	.db 128
	.db 0	; New Instrument (0).
	.db 136
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 148
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 148
	.db 3	; New Instrument (3).
	.db 15
	.db 148
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 150
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 207
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 138
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 143
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 150
	.db 3	; New Instrument (3).
	.db 10
	.db 142
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 17
	.db 128
	.db 0	; New Instrument (0).
	.db 142
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 138
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track5:
	.db 246
	.db 7	; New Instrument (7).
	.db 18	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 24	; Index to an effect block.
	.db 112
	.db 12	; Index to an effect block.
	.db 247
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 181
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 179
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 243
	.db 7	; New Instrument (7).
	.db 15	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 12	; Index to an effect block.
	.db 242
	.db 7	; New Instrument (7).
	.db 21	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 25	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 235
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 107
	.db 1	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 112
	.db 3	; Index to an effect block.
	.db 235
	.db 8	; New Instrument (8).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 236
	.db 7	; New Instrument (7).
	.db 5	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 1	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 20	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 11	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 11	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 231
	.db 7	; New Instrument (7).
	.db 1	; Index to an effect block.
	.db 235
	.db 8	; New Instrument (8).
	.db 11	; Index to an effect block.
	.db 230
	.db 7	; New Instrument (7).
	.db 36	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 39	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 124	; No note, but effects.
	.db 41	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track6:
	.db 246
	.db 7	; New Instrument (7).
	.db 18	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 24	; Index to an effect block.
	.db 112
	.db 12	; Index to an effect block.
	.db 247
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 181
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 179
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 243
	.db 7	; New Instrument (7).
	.db 15	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 12	; Index to an effect block.
	.db 242
	.db 7	; New Instrument (7).
	.db 21	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 25	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 235
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 107
	.db 1	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 112
	.db 3	; Index to an effect block.
	.db 235
	.db 8	; New Instrument (8).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 236
	.db 7	; New Instrument (7).
	.db 5	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 1	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 20	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 11	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 0	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 32	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 174
	.db 8	; New Instrument (8).
	.db 238
	.db 7	; New Instrument (7).
	.db 16	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 176
	.db 8	; New Instrument (8).
	.db 243
	.db 7	; New Instrument (7).
	.db 44	; Index to an effect block.
	.db 238
	.db 8	; New Instrument (8).
	.db 16	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 241
	.db 7	; New Instrument (7).
	.db 31	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 30	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 6	; Index to an effect block.
	.db 242
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 44	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 43	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 11	; Index to an effect block.
	.db 238
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track7:
	.db 195
	.db 1	; New Instrument (1).
	.db 40	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 3
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 3
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 3
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 3
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track8:
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 3
	.db 60	; Waits for 1 line.

	.db 3
	.db 60	; Waits for 1 line.

	.db 3
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 3
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 3
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track9:
	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 2 * 64	; Optimized wait for 4 lines.

	.db 152
	.db 3	; New Instrument (3).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 138
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 139
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track10:
	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 150
	.db 3	; New Instrument (3).
	.db 22
	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 147
	.db 3	; New Instrument (3).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track11:
	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 2 * 64	; Optimized wait for 4 lines.

	.db 152
	.db 3	; New Instrument (3).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 3	; New Instrument (3).
	.db 24
	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 12
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 148
	.db 3	; New Instrument (3).
	.db 24
	.db 27
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 3	; New Instrument (3).
	.db 26
	.db 29
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track12:
	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 10
	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 150
	.db 3	; New Instrument (3).
	.db 10
	.db 60	; Waits for 1 line.

	.db 22
	.db 60	; Waits for 1 line.

	.db 11
	.db 60	; Waits for 1 line.

	.db 23
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track13:
	.db 204
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 216
	.db 6	; New Instrument (6).
	.db 0	; Index to an effect block.
	.db 147
	.db 5	; New Instrument (5).
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 5	; New Instrument (5).
	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 152
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 202
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 131
	.db 1	; New Instrument (1).
	.db 60	; Waits for 1 line.

	.db 139
	.db 6	; New Instrument (6).
	.db 11
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track14:
	.db 216
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 5	; New Instrument (5).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 131
	.db 1	; New Instrument (1).
	.db 60	; Waits for 1 line.

	.db 152
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 3
	.db 214
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 150
	.db 6	; New Instrument (6).
	.db 131
	.db 1	; New Instrument (1).
	.db 60	; Waits for 1 line.

	.db 147
	.db 6	; New Instrument (6).
	.db 147
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track15:
	.db 204
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 216
	.db 6	; New Instrument (6).
	.db 0	; Index to an effect block.
	.db 147
	.db 5	; New Instrument (5).
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 5	; New Instrument (5).
	.db 152
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 152
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 140
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 212
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 152
	.db 3	; New Instrument (3).
	.db 155
	.db 5	; New Instrument (5).
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 6	; New Instrument (6).
	.db 26
	.db 157
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track16:
	.db 216
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 5	; New Instrument (5).
	.db 19
	.db 128
	.db 0	; New Instrument (0).
	.db 150
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 10
	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 5	; New Instrument (5).
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 214
	.db 6	; New Instrument (6).
	.db 0	; Index to an effect block.
	.db 138
	.db 5	; New Instrument (5).
	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 214
	.db 5	; New Instrument (5).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 139
	.db 6	; New Instrument (6).
	.db 60	; Waits for 1 line.

	.db 151
	.db 3	; New Instrument (3).
	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track17:
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 14	; Waits for 15 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 12	; Waits for 13 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 12	; Waits for 13 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 10	; Waits for 11 lines.

	.db 138
	.db 3	; New Instrument (3).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track18:
	.db 204
	.db 3	; New Instrument (3).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 143
	.db 3	; New Instrument (3).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 23	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 205
	.db 3	; New Instrument (3).
	.db 35	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 38	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 124	; No note, but effects.
	.db 23	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track19:
	.db 124	; No note, but effects.
	.db 42	; Index to an effect block.
	.db 61, 22	; Waits for 23 lines.

	.db 124	; No note, but effects.
	.db 45	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track20:
	.db 128
	.db 0	; New Instrument (0).
	.db 61, 52	; Waits for 53 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 3
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track21:
	.db 231
	.db 4	; New Instrument (4).
	.db 8	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 13	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 17	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 14	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 8	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 108
	.db 27	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 46
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 108
	.db 7	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 115
	.db 29	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 115
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 110
	.db 8	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 27	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track22:
	.db 231
	.db 4	; New Instrument (4).
	.db 28	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 103
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 13	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 17	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 14	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 8	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 108
	.db 27	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 46
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 108
	.db 7	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 115
	.db 29	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 115
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 110
	.db 8	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 26	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track23:
	.db 246
	.db 7	; New Instrument (7).
	.db 18	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 24	; Index to an effect block.
	.db 112
	.db 12	; Index to an effect block.
	.db 247
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 181
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 179
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 112
	.db 15	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 243
	.db 7	; New Instrument (7).
	.db 15	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 12	; Index to an effect block.
	.db 242
	.db 7	; New Instrument (7).
	.db 21	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 25	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 243
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 117
	.db 6	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 19	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 235
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 245
	.db 8	; New Instrument (8).
	.db 0	; Index to an effect block.
	.db 107
	.db 1	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 3	; Index to an effect block.
	.db 112
	.db 3	; Index to an effect block.
	.db 235
	.db 8	; New Instrument (8).
	.db 3	; Index to an effect block.
	.db 110
	.db 3	; Index to an effect block.
	.db 236
	.db 7	; New Instrument (7).
	.db 5	; Index to an effect block.
	.db 240
	.db 8	; New Instrument (8).
	.db 1	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 20	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 235
	.db 7	; New Instrument (7).
	.db 11	; Index to an effect block.
	.db 236
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 172
	.db 7	; New Instrument (7).
	.db 235
	.db 8	; New Instrument (8).
	.db 6	; Index to an effect block.
	.db 238
	.db 7	; New Instrument (7).
	.db 0	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 32	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 174
	.db 8	; New Instrument (8).
	.db 238
	.db 7	; New Instrument (7).
	.db 16	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 176
	.db 8	; New Instrument (8).
	.db 243
	.db 7	; New Instrument (7).
	.db 44	; Index to an effect block.
	.db 238
	.db 8	; New Instrument (8).
	.db 16	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 241
	.db 7	; New Instrument (7).
	.db 31	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 30	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 16	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 112
	.db 6	; Index to an effect block.
	.db 242
	.db 8	; New Instrument (8).
	.db 5	; Index to an effect block.
	.db 174
	.db 7	; New Instrument (7).
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 33	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track24:
	.db 204
	.db 3	; New Instrument (3).
	.db 34	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 152
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 3	; New Instrument (3).
	.db 10
	.db 12
	.db 60	; Waits for 1 line.

	.db 15
	.db 128
	.db 0	; New Instrument (0).
	.db 140
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 17
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 133
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 145
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 17
	.db 15
	.db 17
	.db 60	; Waits for 1 line.

	.db 19
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 60	; Waits for 1 line.

	.db 148
	.db 3	; New Instrument (3).
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 136
	.db 3	; New Instrument (3).
	.db 128
	.db 0	; New Instrument (0).
	.db 148
	.db 3	; New Instrument (3).
	.db 60	; Waits for 1 line.

	.db 20
	.db 15
	.db 20
	.db 60	; Waits for 1 line.

	.db 22
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 128
	.db 0	; New Instrument (0).
	.db 143
	.db 3	; New Instrument (3).
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 15
	.db 60	; Waits for 1 line.

	.db 128
	.db 0	; New Instrument (0).
	.db 61, 5	; Waits for 6 lines.

	.db 152
	.db 3	; New Instrument (3).
	.db 12
	.db 60	; Waits for 1 line.

	.db 10
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track25:
	.db 231
	.db 4	; New Instrument (4).
	.db 8	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 13	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 7	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 17	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 14	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 9	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 110
	.db 8	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 108
	.db 27	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 0	; Index to an effect block.
	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 103
	.db 10	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 108
	.db 4	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 46
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 108
	.db 7	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 115
	.db 29	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 62 + 0 * 64	; Optimized wait for 2 lines.

	.db 115
	.db 47	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 115
	.db 46	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 115
	.db 37	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 115
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 115
	.db 0	; Index to an effect block.
	.db 124	; No note, but effects.
	.db 1	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track26:
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 3
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 3
	.db 61, 8	; Waits for 9 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 2	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track27:
	.db 171
	.db 11	; New Instrument (11).
	.db 48
	.db 243
	.db 9	; New Instrument (9).
	.db 0	; Index to an effect block.
	.db 50
	.db 179
	.db 10	; New Instrument (10).
	.db 174
	.db 9	; New Instrument (9).
	.db 178
	.db 10	; New Instrument (10).
	.db 179
	.db 11	; New Instrument (11).
	.db 179
	.db 9	; New Instrument (9).
	.db 50
	.db 179
	.db 11	; New Instrument (11).
	.db 174
	.db 9	; New Instrument (9).
	.db 178
	.db 10	; New Instrument (10).
	.db 179
	.db 11	; New Instrument (11).
	.db 174
	.db 10	; New Instrument (10).
	.db 178
	.db 11	; New Instrument (11).
	.db 51
	.db 46
	.db 171
	.db 9	; New Instrument (9).
	.db 46
	.db 174
	.db 11	; New Instrument (11).
	.db 176
	.db 9	; New Instrument (9).
	.db 174
	.db 10	; New Instrument (10).
	.db 43
	.db 171
	.db 9	; New Instrument (9).
	.db 46
	.db 171
	.db 10	; New Instrument (10).
	.db 176
	.db 9	; New Instrument (9).
	.db 174
	.db 10	; New Instrument (10).
	.db 171
	.db 11	; New Instrument (11).
	.db 176
	.db 10	; New Instrument (10).
	.db 174
	.db 11	; New Instrument (11).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track28:
	.db 174
	.db 11	; New Instrument (11).
	.db 51
	.db 247
	.db 9	; New Instrument (9).
	.db 0	; Index to an effect block.
	.db 53
	.db 183
	.db 10	; New Instrument (10).
	.db 178
	.db 9	; New Instrument (9).
	.db 181
	.db 10	; New Instrument (10).
	.db 183
	.db 11	; New Instrument (11).
	.db 183
	.db 9	; New Instrument (9).
	.db 53
	.db 183
	.db 11	; New Instrument (11).
	.db 178
	.db 9	; New Instrument (9).
	.db 181
	.db 10	; New Instrument (10).
	.db 183
	.db 11	; New Instrument (11).
	.db 178
	.db 10	; New Instrument (10).
	.db 181
	.db 11	; New Instrument (11).
	.db 55
	.db 50
	.db 174
	.db 9	; New Instrument (9).
	.db 50
	.db 178
	.db 11	; New Instrument (11).
	.db 179
	.db 9	; New Instrument (9).
	.db 178
	.db 10	; New Instrument (10).
	.db 46
	.db 174
	.db 9	; New Instrument (9).
	.db 50
	.db 174
	.db 11	; New Instrument (11).
	.db 179
	.db 9	; New Instrument (9).
	.db 178
	.db 10	; New Instrument (10).
	.db 174
	.db 11	; New Instrument (11).
	.db 179
	.db 10	; New Instrument (10).
	.db 178
	.db 11	; New Instrument (11).
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track29:
	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 3
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 62 + 3 * 64	; Optimized wait for 5 lines.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 62 + 1 * 64	; Optimized wait for 3 lines.

	.db 195
	.db 1	; New Instrument (1).
	.db 0	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 22	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 195
	.db 2	; New Instrument (2).
	.db 2	; Index to an effect block.
	.db 60	; Waits for 1 line.

	.db 67
	.db 37	; Index to an effect block.
	.db 67
	.db 2	; Index to an effect block.
	.db 61, 127	; Waits for 128 lines.


Justaddcream_Subsong0_Track30:
	.db 61, 127	; Waits for 128 lines.


; The speed tracks
Justaddcream_Subsong0_SpeedTrack0:
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 14	; Value: 7.
	.db 10	; Value: 5.
	.db 127	; Wait for 64 lines.

; The event tracks
Justaddcream_Subsong0_EventTrack0:
	.db 255	; Wait for 128 lines.

Justaddcream_Subsong0_DisarkByteRegionEnd0:
