@echo off

set Tools=..\..\..\tools

if not exist out md out

:: Assemble
%Tools%\audio\misc\sjasm -s trilo_scc_profile.asm out\trilo_scc.rom

:: Create symbols file
%Tools%\audio\misc\rxrepl -f out\trilo_scc.sym -o out\trilo_scc_rasm.sym -s ": equ [0123456789ABCDEF]{4}([0123456789ABCDEF]{4})h" -r " #\1 B0" -s "\." -r "_"

:: Diassemble
%Tools%\audio\arkos\Disark.exe out\trilo_scc.rom out\trilo_scc.asm --loadAddress 0x8000 --symbolFile out\trilo_scc_rasm.sym --undocumentedOpcodesToBytes --src16bitsValuesInHex --src8bitsValuesInHex --sourceProfile sdcc
%Tools%\audio\misc\fart.exe -C out\trilo_scc.asm ": " ":\n\t"
%Tools%\audio\misc\fart.exe -C out\trilo_scc.asm ","  ", "
%Tools%\audio\misc\fart.exe -C out\trilo_scc.asm ":"  "::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_init:" "replay_init::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_pause:" "replay_pause::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_fade_out:" "replay_fade_out::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_set_SCC_balance:" "replay_set_SCC_balance::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_set_PSG_balance:" "replay_set_PSG_balance::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_equalization:" "replay_equalization::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_loadsong:" "replay_loadsong::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_play_no:" "replay_play_no::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_play:" "replay_play::"
REM %Tools%\audio\misc\fart.exe -C out\trilo_scc.asm "replay_route:" "replay_route::"

:: Create C file
echo ; ____________________________                                                 >  trilo_scc_player.asm
echo ; ██▀▀█▀▀██▀▀▀▀▀▀▀█▀▀█        │  ▄▄▄▄      ▄  ▄▄                               >> trilo_scc_player.asm
echo ; ██  ▀  █▄  ▀██▄ ▀ ▄█ ▄▀▀ █  │   ██  ██▄▀ ▄  ██  ▄█▀▄                         >> trilo_scc_player.asm
echo ; █  █ █  ▀▀  ▄█  █  █ ▀▄█ █▄ │   ██  ██   ██ ▀█▄ ▀█▄▀                         >> trilo_scc_player.asm
echo ; ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀────────┘                                                >> trilo_scc_player.asm
echo ;  by Guillaume 'Aoineko' Blanchard under CC-BY-AS license                     >> trilo_scc_player.asm
echo ;==============================================================================>> trilo_scc_player.asm
echo ; Autogenerated Trilo Tracker player for MSX-GL library                        >> trilo_scc_player.asm
echo ;  on %DATE% at %TIME%                                                         >> trilo_scc_player.asm
echo ;                                                                              >> trilo_scc_player.asm
echo ; Trilo Tracker and the Z80 players are coded and designed                     >> trilo_scc_player.asm
echo ;  by Richard Cornelisse.                                                      >> trilo_scc_player.asm
echo ;==============================================================================>> trilo_scc_player.asm
type out\trilo_scc.asm >> trilo_scc_player.asm

pause











