@echo off

set Tools=..\..\..\tools

if not exist out md out

:: Assemble
%Tools%\audio\misc\sjasm -s trilo_scc_profile.asm out\trilo_scc.rom
%Tools%\audio\misc\rxrepl -f out\trilo_scc.sym -o out\trilo_scc_rasm.sym -s ": equ [0123456789ABCDEF]{4}([0123456789ABCDEF]{4})h" -r " #\1 B0"

:: Diassemble
%Tools%\audio\arkos\Disark.exe out\trilo_scc.rom out\trilo_scc.asm --symbolFile out\trilo_scc_rasm.sym --undocumentedOpcodesToBytes --src16bitsValuesInHex --src8bitsValuesInHex --sourceProfile sdcc

:: Create C file
echo ; ____________________________                                                 >  trilo_scc_player.asm
echo ; ██▀▀█▀▀██▀▀▀▀▀▀▀█▀▀█        │  ▄▄▄▄      ▄  ▄▄                               >> trilo_scc_player.asm
echo ; ██  ▀  █▄  ▀██▄ ▀ ▄█ ▄▀▀ █  │   ██  ██▄▀ ▄  ██  ▄█▀▄                         >> trilo_scc_player.asm
echo ; █  █ █  ▀▀  ▄█  █  █ ▀▄█ █▄ │   ██  ██   ██ ▀█▄ ▀█▄▀                         >> trilo_scc_player.asm
echo ; ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀────────┘                                                >> trilo_scc_player.asm
echo ;  by Guillaume 'Aoineko' Blanchard under CC-BY-AS license                     >> trilo_scc_player.asm
echo ;==============================================================================>> trilo_scc_player.asm
echo ; Autogenerated Trilo Tracker player for MSX-GL library                        >> trilo_scc_player.asm
echo ;  on %DATE% at %TIME%                                                         >> trilo_scc_player.asm
echo ;                                                                              >> trilo_scc_player.asm
echo ; Trilo Tracker and the Z80 players are coded and designed by                  >> trilo_scc_player.asm
echo ;  Cornelisser under ??? License.                                              >> trilo_scc_player.asm
echo ;==============================================================================>> trilo_scc_player.asm
type out\trilo_scc.asm >> trilo_scc_player.asm
