// Generated by MSXgl on 2023-11-25 01:22:21
#pragma once
#include "core.h"

// Langage definition
#define LANG_EN 0
#define LANG_FR 1
#define LANG_JA 2
#define LANG_MAX 3

// Text ID definition
#define TEXT_LANGAGE 0
#define TEXT_MONDAY 1
#define TEXT_TUESDAY 2
#define TEXT_WEDNESDAY 3
#define TEXT_THURSDAY 4
#define TEXT_FRIDAY 5
#define TEXT_SATURDAY 6
#define TEXT_SUNDAY 7
#define TEXT_DATE 8
#define TEXT_START 9
#define TEXT_OPTIONS 10
#define TEXT_EXIT 11
#define TEXT_YEAR 12
#define TEXT_MAX 13

// Localization data table
const c8* const g_LocData[LANG_MAX][TEXT_MAX] =
{
	// EN
	{
		"English", // TEXT_LANGAGE
		"Monday", // TEXT_MONDAY
		"Tuesday", // TEXT_TUESDAY
		"Wednesday", // TEXT_WEDNESDAY
		"Thursday", // TEXT_THURSDAY
		"Friday", // TEXT_FRIDAY
		"Saturday", // TEXT_SATURDAY
		"Sunday", // TEXT_SUNDAY
		"Date", // TEXT_DATE
		"Start", // TEXT_START
		"Options", // TEXT_OPTIONS
		"Exit", // TEXT_EXIT
		NULL, // TEXT_YEAR
	},
	// FR
	{
		"Français", // TEXT_LANGAGE
		"Lundi", // TEXT_MONDAY
		"Mardi", // TEXT_TUESDAY
		"Mercredi", // TEXT_WEDNESDAY
		"Jeudi", // TEXT_THURSDAY
		"Vendredi", // TEXT_FRIDAY
		"Samedi", // TEXT_SATURDAY
		"Dimanche", // TEXT_SUNDAY
		NULL, // TEXT_DATE
		"Commencer", // TEXT_START
		"Options", // TEXT_OPTIONS
		"Quitter", // TEXT_EXIT
		NULL, // TEXT_YEAR
	},
	// JA
	{
		"\xE6\xEB\xFD\x9A\xDE", // TEXT_LANGAGE
		"\x99\xDE\xE2\xF6\x93\xEB\xDE", // TEXT_MONDAY
		"\x96\xF6\x93\xEB\xDE", // TEXT_TUESDAY
		"\x9D\x92\xF6\x93\xEB\xDE", // TEXT_WEDNESDAY
		"\xF3\x98\xF6\x93\xEB\xDE", // TEXT_THURSDAY
		"\x97\xFD\xF6\x93\xEB\xDE", // TEXT_FRIDAY
		"\xE4\xDE\xF6\x93\xEB\xDE", // TEXT_SATURDAY
		"\xE6\xE1\xF6\x93\xEB\xDE", // TEXT_SUNDAY
		NULL, // TEXT_DATE
		"\xBD\xC0\xB0\xC4", // TEXT_START
		"\xB5\xCC\xDF\xBC\xAE\xDD", // TEXT_OPTIONS
		"\x9C\x8D\x93\xF8\x8E\x93", // TEXT_EXIT
		"\x08", // TEXT_YEAR
	},
};